import 'dart:async';
import 'dart:math';
import 'package:adminmrz/adminchat/services/admin_socket_service.dart';
import 'package:adminmrz/adminchat/services/pushservice.dart';
import 'package:adminmrz/settings/call_settings_provider.dart';
import 'package:flutter/material.dart';
import 'package:agora_rtc_engine/agora_rtc_engine.dart';
import 'package:audioplayers/audioplayers.dart';
import 'package:provider/provider.dart';
import 'tokengenerator.dart';

// Call state progression: calling → ringing → connected
enum _CallStatus { calling, ringing, connected, busy }

// Conference participant state
enum _ParticipantStatus { inviting, accepted, declined }

class _ConferenceParticipant {
  final String userId;
  final String name;
  _ParticipantStatus status;
  _ConferenceParticipant({
    required this.userId,
    required this.name,
    this.status = _ParticipantStatus.inviting,
  });
}

class CallScreen extends StatefulWidget {
  final String currentUserId;
  final String currentUserName;
  final String otherUserId;
  final String otherUserName;
  final bool isOutgoingCall;
  /// For incoming calls: the channel name generated by the caller.
  /// When provided (and [isOutgoingCall] is false), this channel is used
  /// instead of generating a new one.
  final String? incomingChannelName;
  final VoidCallback? onMinimize;
  final VoidCallback? onEnd;
  /// Called when the call ends with (callType, status, durationSeconds).
  /// callType is always 'audio'. status is 'answered' or 'missed'.
  final void Function(String callType, String status, int durationSeconds)? onCallEnded;
  /// Called when admin wants to add a participant to the call.
  /// Returns `{'id': userId, 'name': userName}` or null if cancelled.
  final Future<Map<String, String>?> Function()? onAddParticipant;

  const CallScreen({
    super.key,
    required this.currentUserId,
    required this.currentUserName,
    required this.otherUserId,
    required this.otherUserName,
    this.isOutgoingCall = true,
    this.incomingChannelName,
    this.onMinimize,
    this.onEnd,
    this.onCallEnded,
    this.onAddParticipant,
  });

  @override
  State<CallScreen> createState() => _CallScreenState();
}

class _CallScreenState extends State<CallScreen>
    with TickerProviderStateMixin {
  late RtcEngine _engine;

  int _localUid = 0;
  int? _remoteUid;

  String _channel = '';
  String _token = '';

  bool _callActive = false;
  bool _micMuted = false;
  bool _speakerOn = true;
  bool _videoEnabled = false;
  bool _ending = false;
  bool _recipientBusy = false;

  // Video
  Widget? _localVideoView;

  _CallStatus _callStatus = _CallStatus.calling;

  Timer? _timeoutTimer;
  Timer? _callTimer;
  Duration _duration = Duration.zero;

  late AudioPlayer _ringtonePlayer;
  Timer? _ringtoneRepeatTimer;
  StreamSubscription<PlayerState>? _ringtonePlayerStateSubscription;
  bool _isPlayingRingtone = false;

  final AdminSocketService _socketService = AdminSocketService();
  StreamSubscription<Map<String, dynamic>>? _callAcceptedSubscription;
  StreamSubscription<Map<String, dynamic>>? _callRejectedSubscription;
  StreamSubscription<Map<String, dynamic>>? _callCancelledSubscription;
  StreamSubscription<Map<String, dynamic>>? _callEndedSubscription;
  StreamSubscription<Map<String, dynamic>>? _callBusySubscription;
  StreamSubscription<Map<String, dynamic>>? _participantAcceptedSubscription;
  StreamSubscription<Map<String, dynamic>>? _participantRejectedSubscription;

  // Track all remote UIDs in the channel so the call is only ended when
  // the last remote participant disconnects (supports 3-party conference).
  final Set<int> _remoteUids = {};

  // Conference participants added via the plus button
  final List<_ConferenceParticipant> _conferenceParticipants = [];

  // Animation controllers
  late AnimationController _pulseController;
  late AnimationController _signalController;
  late Animation<double> _pulseAnimation;

  // ================= INIT =================
  @override
  void initState() {
    super.initState();
    _ringtonePlayer = AudioPlayer();

    // Pulsing avatar scale animation (when calling/ringing)
    _pulseController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 1200),
    )..repeat(reverse: true);
    _pulseAnimation = Tween<double>(begin: 0.85, end: 1.0).animate(
      CurvedAnimation(parent: _pulseController, curve: Curves.easeInOut),
    );

    // Signal bars cycling animation (when calling/ringing)
    _signalController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 900),
    )..repeat();

    _setupAudio();
    _startCall();
  }

  // ================= AUDIO =================
  void _setupAudio() {
    _ringtonePlayer.setReleaseMode(ReleaseMode.stop);
    _ringtonePlayerStateSubscription = _ringtonePlayer.onPlayerStateChanged.listen((state) {
      if (!mounted) return;
      // Schedule repeat on both .completed (normal end) and .stopped (audio
      // focus lost, e.g. when Agora initializes) so the admin always hears
      // the ringing tone while waiting for the recipient.
      if ((state == PlayerState.completed || state == PlayerState.stopped) &&
          widget.isOutgoingCall &&
          _isPlayingRingtone &&
          !_ending &&
          !_callActive) {
        _scheduleRepeat();
      }
    });
  }

  void _scheduleRepeat() {
    if (!mounted || _ending) return;
    final settings = context.read<CallSettingsProvider>();
    final interval = settings.repeatIntervalSeconds;
    _ringtoneRepeatTimer = Timer(Duration(seconds: interval), () {
      if (!mounted || _ending || _callActive) return;
      _playRingtoneSingle();
    });
  }

  Future<void> _playRingtoneSingle() async {
    if (!widget.isOutgoingCall || _ending || _callActive) return;
    try {
      final settings = context.read<CallSettingsProvider>();
      await _ringtonePlayer.stop();
      await _playPreferredTone(settings);
    } catch (_) {}
  }

  Future<void> _playRingtone() async {
    if (!widget.isOutgoingCall) return;
    try {
      await _ringtonePlayer.stop();
      final settings = context.read<CallSettingsProvider>();
      _isPlayingRingtone = true;
      await _playPreferredTone(settings);
    } catch (_) {}
  }

  Future<void> _playPreferredTone(CallSettingsProvider settings) async {
    if (settings.hasCustomTone) {
      try {
        await _ringtonePlayer.play(
          UrlSource(settings.customToneUrl),
          volume: 1.0,
        );
        return;
      } catch (_) {}
    }

    await _ringtonePlayer.play(
      AssetSource(settings.selectedTone.asset),
      volume: 1.0,
    );
  }

  Future<void> _stopRingtone() async {
    try {
      _ringtoneRepeatTimer?.cancel();
      _ringtoneRepeatTimer = null;
      _ringtonePlayerStateSubscription?.cancel();
      _ringtonePlayerStateSubscription = null;
      _isPlayingRingtone = false;
      await _ringtonePlayer.stop();
    } catch (_) {}
  }

  // ================= START CALL =================
  Future<void> _startCall() async {
    try {
      // Phase 1 – "Calling..." (before notification is sent)
      if (widget.isOutgoingCall) {
        await _playRingtone();
      }

      _localUid = Random().nextInt(999999);

      // For incoming calls use the channel generated by the caller; for
      // outgoing calls generate a fresh channel name.
      if (!widget.isOutgoingCall && widget.incomingChannelName != null) {
        _channel = widget.incomingChannelName!;
      } else {
        _channel =
            'call_${widget.currentUserId}_${widget.otherUserId}_${DateTime.now().millisecondsSinceEpoch}';
      }

      _token = await AgoraTokenService.getToken(
        channelName: _channel,
        uid: _localUid,
      );

      if (widget.isOutgoingCall) {
        final socketReady = await _socketService.ensureConnected();
        await NotificationService.sendCallNotification(
          recipientUserId: widget.otherUserId,
          callerName: widget.currentUserName,
          channelName: _channel,
          callerId: widget.currentUserId,
          callerUid: _localUid.toString(),
          agoraAppId: AgoraTokenService.appId,
          agoraCertificate: 'SERVER_ONLY',
        );
        if (socketReady) {
          _socketService.emitCallInvite(
            recipientId: widget.otherUserId,
            callerId: widget.currentUserId,
            callerName: widget.currentUserName,
            callerImage: '',
            channelName: _channel,
            callerUid: _localUid.toString(),
            callType: 'audio',
            chatRoomId: AdminSocketService.chatRoomId(widget.otherUserId),
          );
        }

        // Phase 2 – transition to "Ringing..." once notification+socket are set
        if (mounted) {
          setState(() => _callStatus = _CallStatus.ringing);
        }

        _callAcceptedSubscription?.cancel();
        _callAcceptedSubscription =
            _socketService.onCallAccepted.listen((data) async {
          if (!mounted || _ending) return;
          final channelName = data['channelName']?.toString();
          if (channelName == _channel) {
            // User accepted the call - stop ringtone and wait for them to join
            await _stopRingtone();
            debugPrint('✅ User accepted call on channel $_channel');
          }
        });

        _callRejectedSubscription?.cancel();
        _callRejectedSubscription =
            _socketService.onCallRejected.listen((data) async {
          if (!mounted || _ending) return;
          if (data['channelName']?.toString() == _channel) {
            await _endCall(notifyPeer: false);
          }
        });

        _callCancelledSubscription?.cancel();
        _callCancelledSubscription =
            _socketService.onCallCancelled.listen((data) async {
          if (!mounted || _ending) return;
          if (data['channelName']?.toString() == _channel) {
            await _endCall(notifyPeer: false);
          }
        });

        _callEndedSubscription?.cancel();
        _callEndedSubscription =
            _socketService.onCallEnded.listen((data) async {
          if (!mounted || _ending) return;
          if (data['channelName']?.toString() == _channel) {
            await _endCall(notifyPeer: false);
          }
        });

        _callBusySubscription?.cancel();
        _callBusySubscription =
            _socketService.onCallBusy.listen((data) async {
          if (!mounted || _ending) return;
          if (data['channelName']?.toString() == _channel) {
            setState(() {
              _recipientBusy = true;
              _callStatus = _CallStatus.busy;
            });
            await _stopRingtone();
            Future.delayed(const Duration(seconds: 2), () {
              if (!_ending) _endCall(notifyPeer: false);
            });
          }
        });
      }

      // ── Conference call participant events ────────────────────────────────
      // Listen for events when admin adds a third participant to the call.
      _participantAcceptedSubscription?.cancel();
      _participantAcceptedSubscription =
          _socketService.onParticipantAcceptedCall.listen((data) {
        if (!mounted || _ending) return;
        if (data['channelName']?.toString() == _channel) {
          final acceptedById = data['acceptedById']?.toString() ?? '';
          setState(() {
            for (final p in _conferenceParticipants) {
              if (p.userId == acceptedById) {
                p.status = _ParticipantStatus.accepted;
              }
            }
          });
        }
      });

      _participantRejectedSubscription?.cancel();
      _participantRejectedSubscription =
          _socketService.onParticipantRejectedCall.listen((data) {
        if (!mounted || _ending) return;
        if (data['channelName']?.toString() == _channel) {
          final rejectedById = data['rejectedById']?.toString() ?? '';
          setState(() {
            for (final p in _conferenceParticipants) {
              if (p.userId == rejectedById) {
                p.status = _ParticipantStatus.declined;
              }
            }
          });
          // Auto-remove declined participant after 4 seconds
          Future.delayed(const Duration(seconds: 4), () {
            if (mounted) {
              setState(() {
                _conferenceParticipants
                    .removeWhere((p) => p.userId == rejectedById &&
                        p.status == _ParticipantStatus.declined);
              });
            }
          });
        }
      });

      // ================= AGORA =================
      _engine = createAgoraRtcEngine();

      await _engine.initialize(RtcEngineContext(
        appId: AgoraTokenService.appId,
        channelProfile: ChannelProfileType.channelProfileCommunication,
      ));

      // Agora enables audio by default after initialize(). Explicitly disable it
      // so the SDK does not take audio focus (and kill the ringtone) before the
      // remote peer joins. It is re-enabled in onUserJoined.
      await _engine.disableAudio();

      _engine.registerEventHandler(
        RtcEngineEventHandler(
          onUserJoined: (_, uid, __) async {
            if (!mounted) return;
            _remoteUids.add(uid);
            // Phase 3 – "Connected" (first remote user joins)
            if (!_callActive) {
              setState(() {
                _remoteUid = uid;
                _callActive = true;
                _callStatus = _CallStatus.connected;
              });
              _pulseController.stop();
              _pulseController.reset();
              _signalController.stop();
              _signalController.reset();
              await _stopRingtone();
              // Enable microphone only after call connects to avoid interrupting ringtone
              await _engine.enableAudio();
              // Now enable microphone publishing
              await _engine.updateChannelMediaOptions(const ChannelMediaOptions(
                publishMicrophoneTrack: true,
                autoSubscribeAudio: true,
                autoSubscribeVideo: true,
              ));
              _startTimer();
            } else {
              // Additional participant joined the conference call – already connected
              setState(() => _remoteUid = uid);
            }
          },

          onUserOffline: (_, uid, __) async {
            _remoteUids.remove(uid);
            // Only end the call when ALL remote participants have left
            if (_remoteUids.isEmpty && !_ending) {
              await _endCall();
            }
          },

          onError: (code, msg) {},
        ),
      );

      await _engine.joinChannel(
        token: _token,
        channelId: _channel,
        uid: _localUid,
        options: const ChannelMediaOptions(
          publishMicrophoneTrack: false, // Keep mic OFF during IVR/ringtone
          autoSubscribeAudio: true,
          autoSubscribeVideo: true,
        ),
      );

      // ================= TIMEOUT =================
      _timeoutTimer = Timer(const Duration(seconds: 30), () async {
        if (_remoteUid == null && !_ending) {
          await NotificationService.sendNotification(
            userId: widget.otherUserId,
            title: '⏰ Missed Call',
            body: 'Missed call from ${widget.currentUserName}',
            data: {
              'type': 'missed_call',
              'callerId': widget.currentUserId,
              'callerName': widget.currentUserName,
              'timestamp': DateTime.now().toIso8601String(),
            },
          );
          await _endCall();
        }
      });
    } catch (_) {
      _exit();
    }
  }

  // ================= TIMER =================
  void _startTimer() {
    _timeoutTimer?.cancel();
    _callTimer = Timer.periodic(const Duration(seconds: 1), (_) {
      if (mounted) {
        setState(() => _duration += const Duration(seconds: 1));
      }
    });
  }

  // ================= VIDEO TOGGLE =================
  Future<void> _toggleVideo() async {
    try {
      if (!_videoEnabled) {
        // Enable video: initialize video engine and start camera preview
        await _engine.enableVideo();
        await _engine.startPreview();
        await _engine.updateChannelMediaOptions(const ChannelMediaOptions(
          publishMicrophoneTrack: true,
          publishCameraTrack: true,
          autoSubscribeAudio: true,
          autoSubscribeVideo: true,
        ));
        final view = AgoraVideoView(
          controller: VideoViewController(
            rtcEngine: _engine,
            canvas: const VideoCanvas(uid: 0),
          ),
        );
        if (mounted) {
          setState(() {
            _videoEnabled = true;
            _localVideoView = view;
          });
        }
      } else {
        // Disable video: stop camera
        await _engine.stopPreview();
        await _engine.disableVideo();
        await _engine.updateChannelMediaOptions(const ChannelMediaOptions(
          publishMicrophoneTrack: true,
          publishCameraTrack: false,
          autoSubscribeAudio: true,
          autoSubscribeVideo: true,
        ));
        if (mounted) {
          setState(() {
            _videoEnabled = false;
            _localVideoView = null;
          });
        }
      }
    } catch (_) {}
  }

  // ================= END CALL =================
  Future<void> _endCall({bool notifyPeer = true}) async {
    if (_ending) return;
    _ending = true;

    try {
      _callTimer?.cancel();
      _timeoutTimer?.cancel();

      await _callRejectedSubscription?.cancel();
      await _callCancelledSubscription?.cancel();
      await _callEndedSubscription?.cancel();
      await _callAcceptedSubscription?.cancel();
      await _callBusySubscription?.cancel();
      await _participantAcceptedSubscription?.cancel();
      await _participantRejectedSubscription?.cancel();
      _callRejectedSubscription = null;
      _callCancelledSubscription = null;
      _callEndedSubscription = null;
      _callAcceptedSubscription = null;
      _callBusySubscription = null;
      _participantAcceptedSubscription = null;
      _participantRejectedSubscription = null;

      if (widget.isOutgoingCall && notifyPeer) {
        if (_callActive) {
          _socketService.emitCallEnd(
            callerId: widget.currentUserId,
            recipientId: widget.otherUserId,
            channelName: _channel,
            callType: 'audio',
            duration: _duration.inSeconds,
          );
        } else {
          _socketService.emitCallCancel(
            recipientId: widget.otherUserId,
            callerId: widget.currentUserId,
            callerName: widget.currentUserName,
            channelName: _channel,
            callType: 'audio',
          );
        }
      }

      await _stopRingtone();
      await _engine.leaveChannel();
      await Future.delayed(const Duration(milliseconds: 300));
      await _engine.release();
    } catch (_) {}

    final String callStatus = _recipientBusy ? 'busy' : (_callActive ? 'answered' : 'missed');
    widget.onCallEnded?.call('audio', callStatus, _duration.inSeconds);

    if (!mounted) return;
    _exit();
  }

  void _exit() {
    if (widget.onEnd != null) {
      widget.onEnd!();
    } else if (mounted) {
      Navigator.pop(context);
    }
  }

  /// Admin adds a third participant to create a conference call
  Future<void> _addParticipant() async {
    if (widget.onAddParticipant == null) return;
    if (!_callActive) return; // Can only add participants to active calls

    try {
      final result = await widget.onAddParticipant!();
      if (result == null || (result['id'] ?? '').isEmpty) return;

      final newParticipantId = result['id']!;
      final newParticipantName = result['name'] ?? 'User';

      // Add to local participants tracking list with "inviting" status
      if (mounted) {
        setState(() {
          // Remove any existing entry for this user (re-invite scenario)
          _conferenceParticipants.removeWhere((p) => p.userId == newParticipantId);
          _conferenceParticipants.add(_ConferenceParticipant(
            userId: newParticipantId,
            name: newParticipantName,
          ));
        });
      }

      // Emit socket event to add participant
      final socketReady = await _socketService.ensureConnected();
      if (socketReady) {
        _socketService.emitAddParticipantToCall(
          newParticipantId: newParticipantId,
          channelName: _channel,
          callType: 'audio',
          adminId: widget.currentUserId,
          adminName: widget.currentUserName,
          newParticipantName: newParticipantName,
          existingParticipantId: widget.otherUserId,
          agoraAppId: AgoraTokenService.appId,
          callerUid: _localUid.toString(),
        );

        // Send push notification as well
        await NotificationService.sendCallNotification(
          recipientUserId: newParticipantId,
          callerName: widget.currentUserName,
          channelName: _channel,
          callerId: widget.currentUserId,
          callerUid: _localUid.toString(),
          agoraAppId: AgoraTokenService.appId,
          agoraCertificate: 'SERVER_ONLY',
        );
      }
    } catch (e) {
      debugPrint('Error adding participant: $e');
    }
  }

  // ================= UI =================
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF0D1117),
      body: Stack(
        children: [
          // ── Main call layout
          Container(
            decoration: const BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment.topCenter,
                end: Alignment.bottomCenter,
                colors: [Color(0xFF1A1A2E), Color(0xFF0D1117)],
              ),
            ),
            child: SafeArea(
              child: Column(
                children: [
                  const SizedBox(height: 48),
                  _buildAvatar(),
                  const SizedBox(height: 24),
                  Text(
                    widget.otherUserName,
                    style: const TextStyle(
                      color: Colors.white,
                      fontSize: 26,
                      fontWeight: FontWeight.w600,
                      letterSpacing: 0.3,
                    ),
                  ),
                  const SizedBox(height: 8),
                  _buildSubtitle(),
                  const SizedBox(height: 20),
                  if (_callStatus != _CallStatus.connected) _buildSignalBars(),
                  // ── Conference participants panel (visible once connected + participants added)
                  _buildParticipantsPanel(),
                  const Spacer(),
                  _buildControls(),
                  const SizedBox(height: 40),
                ],
              ),
            ),
          ),

          // ── Local camera overlay (visible when video mode is on)
          if (_videoEnabled)
            Positioned(
              top: 56,
              right: 16,
              width: 130,
              height: 190,
              child: ClipRRect(
                borderRadius: BorderRadius.circular(12),
                child: _localVideoView ??
                    Container(
                      color: Colors.grey[900],
                      child: const Icon(Icons.videocam, color: Colors.white54, size: 36),
                    ),
              ),
            ),
        ],
      ),
    );
  }

  // ── Status label chip at the top
  Widget _buildStatusLabel() {
    String label;
    Color color;
    switch (_callStatus) {
      case _CallStatus.calling:
        label = 'Calling';
        color = const Color(0xFF6366F1);
        break;
      case _CallStatus.ringing:
        label = 'Ringing';
        color = const Color(0xFF10B981);
        break;
      case _CallStatus.connected:
        label = 'Connected';
        color = const Color(0xFF10B981);
        break;
      case _CallStatus.busy:
        label = 'User Busy';
        color = Colors.orange;
        break;
    }
    return AnimatedSwitcher(
      duration: const Duration(milliseconds: 400),
      child: Container(
        key: ValueKey(label),
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 6),
        decoration: BoxDecoration(
          color: color.withOpacity(0.15),
          borderRadius: BorderRadius.circular(20),
          border: Border.all(color: color.withOpacity(0.4)),
        ),
        child: Text(
          label,
          style: TextStyle(
            color: color,
            fontSize: 13,
            fontWeight: FontWeight.w600,
            letterSpacing: 0.5,
          ),
        ),
      ),
    );
  }

  // ── Pulsing avatar circle
  Widget _buildAvatar() {
    final initials = widget.otherUserName.trim().isNotEmpty
        ? widget.otherUserName.trim()[0].toUpperCase()
        : '?';
    return AnimatedBuilder(
      animation: _pulseAnimation,
      builder: (_, child) {
        final scale = _callStatus == _CallStatus.connected ? 1.0 : _pulseAnimation.value;
        return Transform.scale(
          scale: scale,
          child: child,
        );
      },
      child: Container(
        width: 110,
        height: 110,
        decoration: BoxDecoration(
          shape: BoxShape.circle,
          gradient: const LinearGradient(
            colors: [Color(0xFF6366F1), Color(0xFF8B5CF6)],
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
          ),
          boxShadow: [
            BoxShadow(
              color: const Color(0xFF6366F1).withOpacity(0.45),
              blurRadius: 28,
              spreadRadius: 4,
            ),
          ],
        ),
        child: Center(
          child: Text(
            initials,
            style: const TextStyle(
              color: Colors.white,
              fontSize: 44,
              fontWeight: FontWeight.bold,
            ),
          ),
        ),
      ),
    );
  }

  // ── Subtitle: "Calling…" / "Ringing…" / timer
  Widget _buildSubtitle() {
    String text;
    switch (_callStatus) {
      case _CallStatus.calling:
        text = 'Calling…';
        break;
      case _CallStatus.ringing:
        text = 'Ringing…';
        break;
      case _CallStatus.connected:
        text = _format(_duration);
        break;
      case _CallStatus.busy:
        text = 'User is busy, please try again later';
        break;
    }
    return AnimatedSwitcher(
      duration: const Duration(milliseconds: 350),
      child: Text(
        text,
        key: ValueKey(text),
        style: TextStyle(
          color: Colors.white.withOpacity(0.65),
          fontSize: 16,
        ),
      ),
    );
  }

  // ── Animated signal-strength bars (WhatsApp-style tower indicator)
  static const int _signalBarCount = 4;

  Widget _buildSignalBars() {
    return AnimatedBuilder(
      animation: _signalController,
      builder: (_, __) {
        // Cycle through 1–_signalBarCount active bars based on animation value
        final active = (_signalController.value * _signalBarCount).floor() % _signalBarCount + 1;
        return Row(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.end,
          children: List.generate(_signalBarCount, (i) {
            final barActive = i < active;
            final height = 6.0 + i * 5.0; // 6, 11, 16, 21
            return Padding(
              padding: const EdgeInsets.symmetric(horizontal: 2),
              child: AnimatedContainer(
                duration: const Duration(milliseconds: 200),
                width: 6,
                height: height,
                decoration: BoxDecoration(
                  color: barActive
                      ? const Color(0xFF10B981)
                      : Colors.white.withOpacity(0.2),
                  borderRadius: BorderRadius.circular(2),
                ),
              ),
            );
          }),
        );
      },
    );
  }

  // ── Conference participants panel ───────────────────────────────────────────
  /// Shown in the call body when the admin has added at least one participant.
  Widget _buildParticipantsPanel() {
    // Always show panel when call is active and any participant has been added
    if (!_callActive || _conferenceParticipants.isEmpty) {
      return const SizedBox.shrink();
    }
    final total = _conferenceParticipants.length + 2; // admin + original + added
    return AnimatedSize(
      duration: const Duration(milliseconds: 350),
      curve: Curves.easeOut,
      child: Container(
        margin: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
        padding: const EdgeInsets.all(14),
        decoration: BoxDecoration(
          color: Colors.white.withOpacity(0.07),
          borderRadius: BorderRadius.circular(18),
          border: Border.all(color: Colors.white.withOpacity(0.12)),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Header row
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                  decoration: BoxDecoration(
                    color: const Color(0xFF6366F1).withOpacity(0.18),
                    borderRadius: BorderRadius.circular(10),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      const Icon(Icons.group, color: Color(0xFF6366F1), size: 14),
                      const SizedBox(width: 5),
                      Text(
                        'Conference · $total people',
                        style: const TextStyle(
                          color: Color(0xFF6366F1),
                          fontSize: 11,
                          fontWeight: FontWeight.w700,
                          letterSpacing: 0.3,
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
            const SizedBox(height: 10),
            // Participant chips
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                // You (admin)
                _buildParticipantChip(
                  name: 'You',
                  status: _ParticipantStatus.accepted,
                ),
                // Original callee
                _buildParticipantChip(
                  name: widget.otherUserName,
                  status: _ParticipantStatus.accepted,
                ),
                // Added participants
                ..._conferenceParticipants.map(
                  (p) => _buildParticipantChip(name: p.name, status: p.status),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildParticipantChip({
    required String name,
    required _ParticipantStatus status,
  }) {
    final Color color;
    final IconData icon;
    String? badge;
    switch (status) {
      case _ParticipantStatus.inviting:
        color = const Color(0xFFF59E0B);
        icon = Icons.access_time;
        badge = 'Inviting…';
        break;
      case _ParticipantStatus.accepted:
        color = const Color(0xFF10B981);
        icon = Icons.check_circle;
        break;
      case _ParticipantStatus.declined:
        color = const Color(0xFFEF4444);
        icon = Icons.cancel;
        badge = 'Declined';
        break;
    }
    final truncated = name.length > 14 ? '${name.substring(0, 14)}…' : name;
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
      decoration: BoxDecoration(
        color: color.withOpacity(0.12),
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: color.withOpacity(0.35)),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(icon, color: color, size: 13),
          const SizedBox(width: 5),
          Text(
            truncated,
            style: const TextStyle(
              color: Colors.white,
              fontSize: 12,
              fontWeight: FontWeight.w500,
            ),
          ),
          if (badge != null) ...[
            const SizedBox(width: 4),
            Text(
              badge,
              style: TextStyle(color: color, fontSize: 10, fontWeight: FontWeight.w600),
            ),
          ],
        ],
      ),
    );
  }

  // ── Bottom control buttons row
  Widget _buildControls() {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 20),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: [
          // Mute mic
          _ControlButton(
            icon: _micMuted ? Icons.mic_off : Icons.mic,
            label: _micMuted ? 'Unmute' : 'Mute',
            isActive: _micMuted,
            onTap: () {
              setState(() => _micMuted = !_micMuted);
              _engine.muteLocalAudioStream(_micMuted);
            },
          ),

          // Speaker / Earpiece
          _ControlButton(
            icon: _speakerOn ? Icons.volume_up : Icons.volume_off,
            label: _speakerOn ? 'Speaker' : 'Earpiece',
            isActive: _speakerOn,
            onTap: () {
              setState(() => _speakerOn = !_speakerOn);
              _engine.setEnableSpeakerphone(_speakerOn);
            },
          ),

          // Video mode enable
          _ControlButton(
            icon: _videoEnabled ? Icons.videocam : Icons.videocam_off,
            label: 'Video',
            isActive: _videoEnabled,
            onTap: _toggleVideo,
          ),

          // Call Plus button - add participant (admin only, when call is active)
          if (widget.onAddParticipant != null && _callActive)
            _ControlButton(
              icon: Icons.group_add,
              label: 'Add to Call',
              isActive: true,
              activeColor: const Color(0xFF10B981),
              onTap: _addParticipant,
            ),

          // Minimize (optional)
          if (widget.onMinimize != null)
            _ControlButton(
              icon: Icons.picture_in_picture_alt,
              label: 'Minimize',
              onTap: widget.onMinimize!,
            ),

          // End call (prominent red)
          _EndCallButton(onTap: _endCall),
        ],
      ),
    );
  }

  String _format(Duration d) =>
      '${d.inMinutes}:${(d.inSeconds % 60).toString().padLeft(2, '0')}';

  // ================= DISPOSE =================
  @override
  void dispose() {
    _pulseController.dispose();
    _signalController.dispose();
    _callTimer?.cancel();
    _timeoutTimer?.cancel();
    _ringtoneRepeatTimer?.cancel();
    _ringtonePlayerStateSubscription?.cancel();
    _callAcceptedSubscription?.cancel();
    _callRejectedSubscription?.cancel();
    _callCancelledSubscription?.cancel();
    _callEndedSubscription?.cancel();
    _callBusySubscription?.cancel();
    _participantAcceptedSubscription?.cancel();
    _participantRejectedSubscription?.cancel();

    try {
      _engine.leaveChannel();
      _engine.release();
    } catch (_) {}

    _ringtonePlayer.dispose();
    super.dispose();
  }
}

// ── Generic circular control button
class _ControlButton extends StatelessWidget {
  final IconData icon;
  final String label;
  final VoidCallback onTap;
  final bool isActive;
  final Color? activeColor;

  const _ControlButton({
    required this.icon,
    required this.label,
    required this.onTap,
    this.isActive = false,
    this.activeColor,
  });

  @override
  Widget build(BuildContext context) {
    final resolvedColor = activeColor ?? const Color(0xFF6366F1);
    return GestureDetector(
      onTap: onTap,
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          AnimatedContainer(
            duration: const Duration(milliseconds: 200),
            width: 58,
            height: 58,
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              color: isActive
                  ? resolvedColor.withOpacity(0.85)
                  : Colors.white.withOpacity(0.22),
              border: Border.all(
                color: isActive
                    ? resolvedColor
                    : Colors.white.withOpacity(0.35),
              ),
            ),
            child: Icon(icon, color: Colors.white, size: 26),
          ),
          const SizedBox(height: 6),
          Text(
            label,
            style: TextStyle(
              color: Colors.white.withOpacity(0.7),
              fontSize: 11,
            ),
          ),
        ],
      ),
    );
  }
}

// ── End call button (larger, red)
class _EndCallButton extends StatelessWidget {
  final VoidCallback onTap;
  const _EndCallButton({required this.onTap});

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Container(
            width: 68,
            height: 68,
            decoration: const BoxDecoration(
              shape: BoxShape.circle,
              color: Color(0xFFEF4444),
              boxShadow: [
                BoxShadow(
                  color: Color(0x66EF4444),
                  blurRadius: 16,
                  spreadRadius: 2,
                ),
              ],
            ),
            child: const Icon(Icons.call_end, color: Colors.white, size: 30),
          ),
          const SizedBox(height: 6),
          Text(
            'End',
            style: TextStyle(
              color: Colors.white.withOpacity(0.7),
              fontSize: 11,
            ),
          ),
        ],
      ),
    );
  }
}
