name: ms2026
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  google_fonts: ^6.3.2
  nepali_date_picker:
  nepali_utils:

  # Forms
  intl_phone_field: ^3.2.0
  dropdown_search: ^6.0.2

  # Media
  image_picker: ^1.2.1
  google_mlkit_text_recognition: ^0.13.1
  cunning_document_scanner: ^1.3.3

  # Location
  geolocator: ^11.0.1
  geocoding: ^2.2.0
  webview_flutter: ^4.4.2

  # UI Components
  flutter_card_swiper: ^7.2.0

  # State & Storage
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

  # 🔥 Firebase (all same family, iOS 14+ safe)
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.4
  cloud_functions: ^6.0.4

  # Auth & Network
  google_sign_in: ^6.1.5
  flutter_secure_storage: ^10.0.0
  connectivity_plus: ^6.1.0

  # Audio
  audioplayers:
  flutter_ringtone_player: ^4.0.0
  record:

  # Utilities
  intl: ^0.19.0
  uuid: ^4.4.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.2
  http: ^1.2.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.3.2
  visibility_detector: ^0.4.0+2

  # Socket.IO real-time chat
  socket_io_client: ^2.0.3+1
  http_parser: ^4.0.2

  # Others
  agora_rtc_engine: ^6.5.3
  wakelock_plus: ^1.2.8
  flutter_local_notifications: ^19.5.0
  file_picker: ^10.3.8
  country_code_picker: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
