// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // API key from android/app/google-services.json → client[0].api_key[0].current_key
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtihED7bReUPkjkhAOBFDp3zw3chUTmgU',
    appId: '1:477405059891:android:d38bc46dcbeb60b54d7c46',
    messagingSenderId: '477405059891',
    projectId: 'digitallamicomnp',
    databaseURL: 'https://digitallamicomnp-default-rtdb.firebaseio.com',
    storageBucket: 'digitallamicomnp.firebasestorage.app',
  );

  // API key from ios/Runner/GoogleService-Info.plist → API_KEY
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOygWduFPB-XheH1EnquxMLdhSE0kEyLc',
    appId: '1:477405059891:ios:bfc486eb584d03ed4d7c46',
    messagingSenderId: '477405059891',
    projectId: 'digitallamicomnp',
    databaseURL: 'https://digitallamicomnp-default-rtdb.firebaseio.com',
    storageBucket: 'digitallamicomnp.firebasestorage.app',
    iosBundleId: 'com.digitallami.appz',
  );

  // Web app configuration.
  // apiKey  → same Firebase project; browser-unrestricted key (matches web/firebase-messaging-sw.js).
  // appId   → Registered Web app from Firebase Console
  //           console.firebase.google.com → digitallamicomnp → Project settings
  //           → Your apps → Web app (matches web/firebase-messaging-sw.js)
  // measurementId → optional (Google Analytics). Leave empty or fill from Console.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6BqEPNDcAZORqSrKcMUEpxRagJbZci9w',
    appId: '1:477405059891:web:86dc05c92a2406b84d7c46',
    messagingSenderId: '477405059891',
    projectId: 'digitallamicomnp',
    authDomain: 'digitallamicomnp.firebaseapp.com',
    databaseURL: 'https://digitallamicomnp-default-rtdb.firebaseio.com',
    storageBucket: 'digitallamicomnp.firebasestorage.app',
  );
}
