import 'dart:async';
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:ms2026/Auth/Screen/signupscreen10.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../../../ReUsable/dropdownwidget.dart';
import '../../../service/partner_age_preferences.dart';
import '../../../service/updatepage.dart';
import 'package:ms2026/config/app_endpoints.dart';



// Data Models
class Country {
  final String id;
  final String name;

  Country({required this.id, required this.name});
}

class StateModel {
  final int id;
  final String name;
  final String countryId;

  StateModel({required this.id, required this.name, required this.countryId});
}

class City {
  final int id;
  final String name;
  final int stateId;

  City({required this.id, required this.name, required this.stateId});
}

class PartnerPreferencesPagee extends StatefulWidget {
  const PartnerPreferencesPagee({
    super.key,
    this.initialData,
  });

  final Map<String, dynamic>? initialData;

  @override
  State<PartnerPreferencesPagee> createState() => _PartnerPreferencesPageeState();
}

class _PartnerPreferencesPageeState extends State<PartnerPreferencesPagee> {
  bool submitted = false;
  bool isLoading = false;

  // Age Range
  double _minAge = 22.0;
  double _maxAge = 60.0;
  double _minPreferredAgeLimit = PartnerAgePreferenceBounds.minimumAllowedAge.toDouble();
  double _maxPreferredAgeLimit = 60.0;

  // Height Range
  double _minHeight = 121.0;
  double _maxHeight = 215.0;

  // Basic Preferences
  List<String> _selectedMaritalStatus = [];
  String? _selectedProfileWithChildren;
  List<String> _selectedFamilyType = [];

  // Community Details
  List<String> _selectedReligion = [];
  List<String> _selectedCast = [];
  List<String> _selectedsubCast = [];
  List<String> _selectedMotherTongue = [];

  // Astrological Details
  String? _selectedHoroscopeBelief;
  String? _selectedManglik;

  // Location Details - Loaded from API
  List<Country> _countries = [];
  List<StateModel> _allStates = [];
  List<City> _allCities = [];
  List<String> _selectedCountry = [];
  List<String> _selectedState = [];
  List<String> _selectedCity = [];

  // Education Details
  List<String> _selectedQualification = [];
  List<String> _selectedEducationMedium = [];

  // Profession Details
  List<String> _selectedProfession = [];
  List<String> _selectedWorkingWith = [];
  List<String> _selectedAnnualIncome = [];

  // Other Details
  List<String> _selectedDiet = [];
  String? _selectedSmokeAcceptance;
  String? _selectedAlcoholAcceptance;
  String? _selectedDisabilityAcceptance;
  List<String> _selectedComplexion = [];
  List<String> _selectedBodyType = [];
  final TextEditingController _otherExpectationsController = TextEditingController();

  // Auto-generated expectations
  final List<String> _autoGeneratedExpectations = [];

  // Loading states
  bool _loadingCountries = false;
  bool _loadingStates = false;
  bool _loadingCities = false;

  // Error messages
  final Map<String, String> _errors = {
    'maritalStatus': '',
    'profileWithChildren': '',
    'familyType': '',
    'religion': '',
    'cast': '',
    'subCast': '',
    'motherTongue': '',
    'horoscopeBelief': '',
    'manglik': '',
    'country': '',
    'state': '',
    'city': '',
    'qualification': '',
    'educationMedium': '',
    'profession': '',
    'workingWith': '',
    'annualIncome': '',
    'diet': '',
    'smokeAcceptance': '',
    'alcoholAcceptance': '',
    'disabilityAcceptance': '',
    'complexion': '',
    'bodyType': '',
    'otherExpectations': '',
  };

  @override
  void initState() {
    super.initState();
    _loadCountries();
    _loadSavedPreferences();
  }

  double _clampAgeValue(double value) {
    if (value < _minPreferredAgeLimit) {
      return _minPreferredAgeLimit;
    }

    if (value > _maxPreferredAgeLimit) {
      return _maxPreferredAgeLimit;
    }

    return value;
  }

  void _applyNormalizedAgeRange({
    double? minAge,
    double? maxAge,
  }) {
    final normalizedMin = _clampAgeValue(minAge ?? _minAge);
    final normalizedMax = _clampAgeValue(maxAge ?? _maxAge);

    if (normalizedMin > normalizedMax) {
      _minAge = normalizedMax;
      _maxAge = normalizedMin;
      return;
    }

    _minAge = normalizedMin;
    _maxAge = normalizedMax;
  }

  void _applyAgeBoundsFromUserData(Map<String, dynamic> userData) {
    final bounds = resolvePartnerAgePreferenceBounds(
      userData: userData,
      fallbackMaxAge: _maxPreferredAgeLimit.toInt(),
    );

    _minPreferredAgeLimit = bounds.minAge.toDouble();
    _maxPreferredAgeLimit = bounds.maxAge.toDouble();
    _applyNormalizedAgeRange();
  }

  List<String> _asPreferenceList(dynamic value) {
    if (value == null) return ['Any'];
    if (value is List) {
      final normalized = value
          .map((item) => item.toString().trim())
          .where((item) => item.isNotEmpty)
          .toList();
      return normalized.isEmpty ? ['Any'] : normalized;
    }

    final normalized = value
        .toString()
        .split(',')
        .map((item) => item.trim())
        .where((item) => item.isNotEmpty)
        .toList();
    return normalized.isEmpty ? ['Any'] : normalized;
  }

  void _applyPreferenceData(Map<String, dynamic> data) {
    setState(() {
      final savedMinAge = data['minage']?.toString();
      final savedMaxAge = data['maxage']?.toString();

      _applyNormalizedAgeRange(
        minAge: savedMinAge == null
            ? _minPreferredAgeLimit
            : (double.tryParse(savedMinAge) ?? _minPreferredAgeLimit),
        maxAge: savedMaxAge == null
            ? _maxPreferredAgeLimit
            : (double.tryParse(savedMaxAge) ?? _maxPreferredAgeLimit),
      );

      _minHeight = double.tryParse(data['minheight']?.toString() ?? '') ?? 121;
      _maxHeight = double.tryParse(data['maxheight']?.toString() ?? '') ?? 215;
      _selectedMaritalStatus = _asPreferenceList(data['maritalstatus']);
      _selectedProfileWithChildren = data['profilewithchild']?.toString();
      _selectedFamilyType = _asPreferenceList(data['familytype']);
      _selectedReligion = _asPreferenceList(data['religion']);
      _selectedCast = _asPreferenceList(data['caste']);
      _selectedsubCast = _asPreferenceList(data['subcaste'] ?? data['subcast']);
      _selectedMotherTongue = _asPreferenceList(data['mothertongue']); // Corrected field name
      _selectedHoroscopeBelief = data['horoscopebelief']?.toString(); // Corrected field name
      _selectedManglik = data['manglik']?.toString();
      _selectedCountry = _asPreferenceList(data['country']);
      _selectedState = _asPreferenceList(data['state']);
      _selectedCity = _asPreferenceList(data['city']);
      _selectedQualification = _asPreferenceList(data['qualification']);
      _selectedEducationMedium = _asPreferenceList(data['educationmedium']);
      _selectedProfession = _asPreferenceList(data['profession']); // Corrected field name
      _selectedWorkingWith = _asPreferenceList(data['workingwith']);
      _selectedAnnualIncome = _asPreferenceList(data['annualincome']);
      _selectedDiet = _asPreferenceList(data['diet']);
      _selectedSmokeAcceptance = data['smokeaccept']?.toString();
      _selectedAlcoholAcceptance = data['drinkaccept']?.toString();
      _selectedDisabilityAcceptance = data['disabilityaccept']?.toString();
      _selectedComplexion = _asPreferenceList(data['complexion']);
      _selectedBodyType = _asPreferenceList(data['bodytype']);
      _otherExpectationsController.text = data['otherexpectation']?.toString() ?? '';
      isLoading = false;
    });

    if (_countries.isNotEmpty && _selectedCountry.isNotEmpty && !_hasAnySelected(_selectedCountry)) {
      _loadStatesForCountries(_getCountryIds(_selectedCountry));
    }
    if (_allStates.isNotEmpty && _selectedState.isNotEmpty && !_hasAnySelected(_selectedState)) {
      _loadCitiesForStates(_getStateIds(_selectedState));
    }
    _updateAutoGeneratedExpectations();
  }

  // API Service Methods
  Future<void> _loadCountries() async {
    setState(() => _loadingCountries = true);
    try {
      final response = await http.get(
        Uri.parse("${kApiBaseUrl}/Api3/countries.php"),
      ).timeout(const Duration(seconds: 30));

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        if (data['status'] == 'success') {
          setState(() {
            _countries = (data['data'] as List)
                .map((item) => Country(id: item['id'].toString(), name: item['name']))
                .toList();
            // Add "Any" option at the beginning
            _countries.insert(0, Country(id: '0', name: 'Any'));
          });

          if (_selectedCountry.isNotEmpty && !_hasAnySelected(_selectedCountry)) {
            await _loadStatesForCountries(_getCountryIds(_selectedCountry));
          }
          if (_selectedState.isNotEmpty && !_hasAnySelected(_selectedState) && _allStates.isNotEmpty) {
            await _loadCitiesForStates(_getStateIds(_selectedState));
          }
        }
      } else {
        _showError("Failed to load countries. Please try again.");
      }
    } on TimeoutException {
      _showError("Timeout loading countries. Please check your connection.");
    } catch (e) {
      print("Error loading countries: $e");
      _showError("Error loading countries. Please try again.");
    } finally {
      setState(() => _loadingCountries = false);
    }
  }

  Future<void> _loadStatesForCountries(List<String> countryIds) async {
    if (countryIds.isEmpty || countryIds.contains('Any')) {
      setState(() => _allStates.clear());
      return;
    }

    setState(() => _loadingStates = true);
    final List<StateModel> loadedStates = [];

    try {
      for (final countryId in countryIds) {
        if (countryId == '0') continue; // Skip "Any"

        final response = await http.get(
          Uri.parse("${kApiBaseUrl}/Api3/states.php?country_id=$countryId"),
        ).timeout(const Duration(seconds: 30));

        if (response.statusCode == 200) {
          final data = jsonDecode(response.body);
          if (data['status'] == 'success') {
            final states = (data['data'] as List)
                .map((item) => StateModel(
              id: item['id'],
              name: item['name'],
              countryId: countryId,
            ))
                .toList();
            loadedStates.addAll(states);
          }
        }
      }

      setState(() {
        _allStates = loadedStates;
        // Add "Any" option if we have states
        if (_allStates.isNotEmpty) {
          _allStates.insert(0, StateModel(id: 0, name: 'Any', countryId: '0'));
        }
      });
    } on TimeoutException {
      _showError("Timeout loading states. Please try again.");
    } catch (e) {
      print("Error loading states: $e");
      _showError("Error loading states. Please try again.");
    } finally {
      setState(() => _loadingStates = false);
    }
  }

  Future<void> _loadCitiesForStates(List<String> stateIds) async {
    if (stateIds.isEmpty || stateIds.contains('Any')) {
      setState(() => _allCities.clear());
      return;
    }

    setState(() => _loadingCities = true);
    final List<City> loadedCities = [];

    try {
      for (final stateId in stateIds) {
        if (stateId == 'Any' || stateId == '0') continue;

        final response = await http.get(
          Uri.parse("${kApiBaseUrl}/Api3/cities.php?state_id=$stateId"),
        ).timeout(const Duration(seconds: 30));

        if (response.statusCode == 200) {
          final data = jsonDecode(response.body);
          if (data['status'] == 'success') {
            final cities = (data['data'] as List)
                .map((item) => City(
              id: item['id'],
              name: item['name'],
              stateId: int.parse(stateId),
            ))
                .toList();
            loadedCities.addAll(cities);
          }
        }
      }

      setState(() {
        _allCities = loadedCities;
        // Add "Any" option if we have cities
        if (_allCities.isNotEmpty) {
          _allCities.insert(0, City(id: 0, name: 'Any', stateId: 0));
        }
      });
    } on TimeoutException {
      _showError("Timeout loading cities. Please try again.");
    } catch (e) {
      print("Error loading cities: $e");
      _showError("Error loading cities. Please try again.");
    } finally {
      setState(() => _loadingCities = false);
    }
  }

  // Helper methods
  bool _hasAnySelected(List<String> list) {
    return list.contains('Any');
  }

  List<String> _getCountryIds(List<String> selectedNames) {
    if (selectedNames.contains('Any')) return ['0'];

    return selectedNames
        .map((name) {
          final country = _countries.firstWhere(
            (c) => c.name == name,
            orElse: () => Country(id: '', name: name),
          );
          return country.id;
        })
        .where((id) => id.isNotEmpty)
        .toList();
  }

  List<String> _getStateIds(List<String> selectedNames) {
    if (selectedNames.contains('Any')) return ['0'];

    return selectedNames
        .map((name) {
          final state = _allStates.firstWhere(
            (s) => s.name == name,
            orElse: () => StateModel(id: 0, name: name, countryId: ''),
          );
          return state.id == 0 ? '' : state.id.toString();
        })
        .where((id) => id.isNotEmpty)
        .toList();
  }

  List<String> _getCityIds(List<String> selectedNames) {
    if (selectedNames.contains('Any')) return ['0'];

    return selectedNames
        .map((name) {
          final city = _allCities.firstWhere(
            (c) => c.name == name,
            orElse: () => City(id: 0, name: name, stateId: 0),
          );
          return city.id == 0 ? '' : city.id.toString();
        })
        .where((id) => id.isNotEmpty)
        .toList();
  }

  void _updateAutoGeneratedExpectations() {
    List<String> expectations = [];

    // Age expectations
    expectations.add('Looking for a partner aged between ${_minAge.toInt()} and ${_maxAge.toInt()} years.');

    // Height expectations
    expectations.add('Preferred height range: ${_minHeight.toInt()} cm to ${_maxHeight.toInt()} cm.');

    // Marital status
    if (_selectedMaritalStatus.isNotEmpty && !_hasAnySelected(_selectedMaritalStatus)) {
      expectations.add('Marital status preference: ${_selectedMaritalStatus.join(", ")}.');
    }

    // Family type
    if (_selectedFamilyType.isNotEmpty && !_hasAnySelected(_selectedFamilyType)) {
      expectations.add('Preferred family type: ${_selectedFamilyType.join(", ")}.');
    }

    // Religion
    if (_selectedReligion.isNotEmpty && !_hasAnySelected(_selectedReligion)) {
      expectations.add('Religion: ${_selectedReligion.join(", ")}.');
    }

    // Community preferences
    if (_selectedCast.isNotEmpty && !_hasAnySelected(_selectedCast)) {
      expectations.add('Community/caste preference: ${_selectedCast.join(", ")}.');
    }

    // Mother tongue
    if (_selectedMotherTongue.isNotEmpty && !_hasAnySelected(_selectedMotherTongue)) {
      expectations.add('Mother tongue preference: ${_selectedMotherTongue.join(", ")}.');
    }

    // Location preferences
    if (_selectedCountry.isNotEmpty && !_hasAnySelected(_selectedCountry)) {
      final countryNames = _selectedCountry.map((id) {
        if (id == 'Any') return 'Any';
        final country = _countries.firstWhere((c) => c.id == id, orElse: () => Country(id: '', name: id));
        return country.name;
      }).toList();
      expectations.add('Preferred country: ${countryNames.join(", ")}.');
    }

    // Education
    if (_selectedQualification.isNotEmpty && !_hasAnySelected(_selectedQualification)) {
      expectations.add('Educational qualification: ${_selectedQualification.join(", ")}.');
    }

    // Profession
    if (_selectedProfession.isNotEmpty && !_hasAnySelected(_selectedProfession)) {
      expectations.add('Profession preference: ${_selectedProfession.join(", ")}.');
    }

    // Income
    if (_selectedAnnualIncome.isNotEmpty && !_hasAnySelected(_selectedAnnualIncome)) {
      expectations.add('Annual income expectation: ${_selectedAnnualIncome.join(", ")}.');
    }

    // Lifestyle preferences
    if (_selectedDiet.isNotEmpty && !_hasAnySelected(_selectedDiet)) {
      expectations.add('Diet preference: ${_selectedDiet.join(", ")}.');
    }

    // Physical preferences
    if (_selectedComplexion.isNotEmpty && !_hasAnySelected(_selectedComplexion)) {
      expectations.add('Complexion preference: ${_selectedComplexion.join(", ")}.');
    }

    if (_selectedBodyType.isNotEmpty && !_hasAnySelected(_selectedBodyType)) {
      expectations.add('Body type preference: ${_selectedBodyType.join(", ")}.');
    }

    // Add smoke/alcohol preferences if selected
    if (_selectedSmokeAcceptance != null && _selectedSmokeAcceptance != 'Any') {
      expectations.add('Smoking acceptance: $_selectedSmokeAcceptance.');
    }

    if (_selectedAlcoholAcceptance != null && _selectedAlcoholAcceptance != 'Any') {
      expectations.add('Alcohol acceptance: $_selectedAlcoholAcceptance.');
    }

    if (_selectedDisabilityAcceptance != null && _selectedDisabilityAcceptance != 'Any') {
      expectations.add('Disability acceptance: $_selectedDisabilityAcceptance.');
    }

    // Astrological preferences
    if (_selectedHoroscopeBelief != null && _selectedHoroscopeBelief != 'Any') {
      expectations.add('Horoscope belief: $_selectedHoroscopeBelief.');
    }

    if (_selectedManglik != null && _selectedManglik != 'Any') {
      expectations.add('Manglik preference: $_selectedManglik.');
    }

    setState(() {
      _autoGeneratedExpectations.clear();
      _autoGeneratedExpectations.addAll(expectations);

      // Update the expectations controller with auto-generated text
      if (_autoGeneratedExpectations.isNotEmpty) {
        _otherExpectationsController.text = _autoGeneratedExpectations.join('\n');
      }
    });
  }

  // Dropdown options
  final List<String> _maritalStatusOptions = [
    'Any',
    'Single',
    'Divorced',
    'Widowed',
    'Never Married',
  ];

  final List<String> _childrenOptions = [
    'Any',
    'No child',
    'One',
    'Two or more',
  ];

  final List<String> _familyTypeOptions = [
    'Any',
    'Joint Family',
    'Nuclear Family',
    'Single Parent',
    'Extended Family',
  ];

  final List<String> _religionOptions = [
    'Any',
    'Hindu',
    'Muslim',
    'Christian',
    'Sikh',
    'Buddhist',
    'Jain',
  ];

  final List<String> _castOptions = [
    'Any',
    'Brahmin',
    'Chhetri',
    'Newar',
    'Gurung',
    'Tamang',
    'Rai',
    'Limbu',
    'Magar',
    'Tharu',
    'Sherpa',
  ];

  final List<String> _subcastOptions = [
    'Any',
    'Sherpa',
    'Thakali',
    'Bhote',
    'Lopa',
    'Manange',
    'Dolpo',
    'Brahmin',
    'Chhetri',
    'Newar',
    'Gurung',
    'Tamang',
    'Rai',
    'Limbu',
    'Magar',
    'Sunuwar',
    'Yakkha',
    'Thami',
    'Chepang',
    'Bhujel',
    'Danuwar',
    'Jirel',
    'Lepcha',
    'Tharu',
    'Yadav',
    'Koiri',
    'Kurmi',
    'Rajput',
    'Teli',
    'Mallah',
    'Baniya',
    'Musalman (Muslim)',
    'Kalwar',
    'Hajam',
    'Dhimal',
    'Rajbanshi',
    'Satar',
    'Marwadi',
    'Kami',
    'Damai',
    'Sarki',
    'Chamar',
    'Dusadh',
    'Mushahar',
    'Pode',
    'Badi',
    'Sanyasi',
    'Giri',
    'Thakuri',
    'Kumal',
    'Majhi',
    'Kewat',
    'Gaine',
    'Sikh',
    'Jain',
  ];

  final List<String> _motherTongueOptions = [
    'Any',
    'Nepali',
    'Maithili',
    'Bhojpuri',
    'Tharu',
    'Tamang',
    'Newari',
    'Magar',
    'Gurung',
    'Limbu',
    'Rai',
    'Sherpa',
  ];

  final List<String> _beliefOptions = [
    'Any',
    'Yes',
    'No',
    'Doesn\'t matter'
  ];

  final List<String> _qualificationOptions = [
    'Any',
    'SEE/SLC',
    '+2/Intermediate',
    'Diploma',
    'Bachelor',
    'Master',
    'PhD',
  ];

  final List<String> _educationMediumOptions = [
    'Any',
    'English',
    'Nepali',
    'Hindi',
  ];

  final List<String> _professionOptions = [
    'Any',
    'Government Job',
    'Private Job',
    'Business',
    'Doctor',
    'Engineer',
    'Teacher',
    'Student',
  ];

  final List<String> _workingWithOptions = [
    'Any',
    'Private Company',
    'Government',
    'NGO/INGO',
    'Self Employed',
    'Family Business',
  ];

  final List<String> _annualIncomeOptions = [
    'Any',
    'Below 2 Lakhs',
    '2-5 Lakhs',
    '5-10 Lakhs',
    '10-20 Lakhs',
    '20-50 Lakhs',
    '50 Lakhs - 1 Crore',
    'Above 1 Crore',
  ];

  final List<String> _dietOptions = [
    'Any',
    'Vegetarian',
    'Non-Vegetarian',
    'Eggetarian',
    'Vegan',
    'Jain',
  ];

  final List<String> _complexionOptions = [
    'Any',
    'Very Fair',
    'Fair',
    'Wheatish',
    'Olive',
    'Brown',
    'Dark',
  ];

  final List<String> _bodyTypeOptions = [
    'Any',
    'Slim',
    'Athletic',
    'Average',
    'Heavy',
    'Muscular',
  ];

  // Validation methods
  bool _validateRequiredList(List<String> list, String fieldName) {
    if (list.isEmpty) {
      _errors[fieldName] = 'Please select at least one option';
      return false;
    }
    _errors[fieldName] = '';
    return true;
  }

  bool _validateRequired(String? value, String fieldName) {
    if (value == null || value.isEmpty) {
      _errors[fieldName] = 'This field is required';
      return false;
    }
    _errors[fieldName] = '';
    return true;
  }

  bool _validateForm() {
    bool isValid = true;

    // Clear all errors
    _errors.forEach((key, value) {
      _errors[key] = '';
    });

    // Basic Preferences validation
    if (!_validateRequiredList(_selectedMaritalStatus, 'maritalStatus')) {
      isValid = false;
    }

    // Profile with children validation (only required if not single/any)
    if (!_hasAnySelected(_selectedMaritalStatus) && !_selectedMaritalStatus.contains('Single')) {
      if (!_validateRequired(_selectedProfileWithChildren, 'profileWithChildren')) {
        isValid = false;
      }
    } else {
      // Default to "No child" for single or any
      _selectedProfileWithChildren = 'No child';
    }

    if (!_validateRequiredList(_selectedFamilyType, 'familyType')) {
      isValid = false;
    }

    // Community Details validation
    if (!_validateRequiredList(_selectedReligion, 'religion')) {
      isValid = false;
    }
    if (!_validateRequiredList(_selectedCast, 'cast')) {
      isValid = false;
    }
    if (!_validateRequiredList(_selectedsubCast, 'subCast')) {
      isValid = false;
    }
    if (!_validateRequiredList(_selectedMotherTongue, 'motherTongue')) {
      isValid = false;
    }

    // Astrological Details validation
    if (!_validateRequired(_selectedHoroscopeBelief, 'horoscopeBelief')) {
      isValid = false;
    }
    if (!_validateRequired(_selectedManglik, 'manglik')) {
      isValid = false;
    }

    // Location Details validation
    if (!_validateRequiredList(_selectedCountry, 'country')) {
      isValid = false;
    }
    if (!_hasAnySelected(_selectedCountry) && !_validateRequiredList(_selectedState, 'state')) {
      isValid = false;
    }
    if (!_hasAnySelected(_selectedState) && !_validateRequiredList(_selectedCity, 'city')) {
      isValid = false;
    }

    // Education Details validation
    if (!_validateRequiredList(_selectedQualification, 'qualification')) {
      isValid = false;
    }
    if (!_validateRequiredList(_selectedEducationMedium, 'educationMedium')) {
      isValid = false;
    }

    // Profession Details validation
    if (!_validateRequiredList(_selectedProfession, 'profession')) {
      isValid = false;
    }
    if (!_validateRequiredList(_selectedWorkingWith, 'workingWith')) {
      isValid = false;
    }
    if (!_validateRequiredList(_selectedAnnualIncome, 'annualIncome')) {
      isValid = false;
    }

    // Other Details validation
    if (!_validateRequiredList(_selectedDiet, 'diet')) {
      isValid = false;
    }
    if (!_validateRequired(_selectedSmokeAcceptance, 'smokeAcceptance')) {
      isValid = false;
    }
    if (!_validateRequired(_selectedAlcoholAcceptance, 'alcoholAcceptance')) {
      isValid = false;
    }
    if (!_validateRequired(_selectedDisabilityAcceptance, 'disabilityAcceptance')) {
      isValid = false;
    }
    if (!_validateRequiredList(_selectedComplexion, 'complexion')) {
      isValid = false;
    }
    if (!_validateRequiredList(_selectedBodyType, 'bodyType')) {
      isValid = false;
    }

    setState(() {});
    return isValid;
  }

  // Handler methods
  void _handleCountryChange(List<String> selectedItems) {
    setState(() {
      _selectedCountry = selectedItems;
      _errors['country'] = '';

      // Reset states and cities when countries change
      _selectedState = ['Any'];
      _selectedCity = ['Any'];
      _allStates.clear();
      _allCities.clear();
    });

    // Load states for selected countries
    _loadStatesForCountries(_getCountryIds(selectedItems));
    _updateAutoGeneratedExpectations();
  }

  void _handleStateChange(List<String> selectedItems) {
    setState(() {
      _selectedState = selectedItems;
      _errors['state'] = '';

      // Reset cities when states change
      _selectedCity = ['Any'];
      _allCities.clear();
    });

    // Load cities for selected states
    _loadCitiesForStates(_getStateIds(selectedItems));
    _updateAutoGeneratedExpectations();
  }

  void _handleCityChange(List<String> selectedItems) {
    setState(() {
      _selectedCity = selectedItems;
      _errors['city'] = '';
    });

    _updateAutoGeneratedExpectations();
  }

  void _handleMultiSelectChange(List<String> selectedItems, String fieldName, Function(List<String>) updateFunction) {
    // If "Any" is selected, clear all other selections and only keep "Any"
    if (selectedItems.contains('Any')) {
      selectedItems = ['Any'];
    }
    // If something else is selected and "Any" was previously selected, remove "Any"
    else if (selectedItems.isNotEmpty) {
      selectedItems.remove('Any');
    }

    updateFunction(selectedItems);
    _updateAutoGeneratedExpectations();
  }

  void _handleSingleSelectChange(String? value, String fieldName, Function(String?) updateFunction) {
    updateFunction(value);
    _updateAutoGeneratedExpectations();
  }

  @override
  Widget build(BuildContext context) {
    final rawAgeDivisions = (_maxPreferredAgeLimit - _minPreferredAgeLimit).round();
    final ageDivisions = rawAgeDivisions < 1 ? 1 : rawAgeDivisions;

    return Scaffold(
      backgroundColor: const Color(0xFFF5F6FA),
      appBar: PreferredSize(
        preferredSize: const Size.fromHeight(64),
        child: Container(
          decoration: const BoxDecoration(
            gradient: LinearGradient(
              colors: [Color(0xFFE64B37), Color(0xFFE62255)],
              begin: Alignment.centerLeft,
              end: Alignment.centerRight,
            ),
          ),
          child: SafeArea(
            child: Padding(
              padding: const EdgeInsets.symmetric(horizontal: 4, vertical: 8),
              child: Row(
                children: [
                  IconButton(
                    icon: const Icon(Icons.arrow_back_ios_new, color: Colors.white, size: 20),
                    onPressed: () => Navigator.pop(context),
                  ),
                  const Expanded(
                    child: Text(
                      'Partner Preferences',
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 18,
                        fontWeight: FontWeight.w700,
                        letterSpacing: 0.3,
                      ),
                      textAlign: TextAlign.center,
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.only(right: 12),
                    child: _progressBubble(0.45, "45%"),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
      bottomNavigationBar: _buildBottomBar(),
      body: Stack(
        children: [
          SingleChildScrollView(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
            child: Column(
              children: [
                _buildHeroHeader(),
                const SizedBox(height: 20),

                // Physical Preferences Card
                _buildSectionCard(
                  icon: Icons.accessibility_new_rounded,
                  iconColor: const Color(0xFFE64B37),
                  title: 'Physical Preferences',
                  children: [
                    _buildSubLabel('Age Range'),
                    const SizedBox(height: 8),
                    _buildRangeSlider(
                      minValue: _minAge,
                      maxValue: _maxAge,
                      min: _minPreferredAgeLimit,
                      max: _maxPreferredAgeLimit,
                      divisions: ageDivisions,
                      labelBuilder: (value) => '${value.toInt()}',
                      onChanged: (min, max) {
                        setState(() {
                          _applyNormalizedAgeRange(minAge: min, maxAge: max);
                          _updateAutoGeneratedExpectations();
                        });
                      },
                    ),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        _buildRangeLabel('${_minAge.toInt()} yrs'),
                        _buildRangeLabel('${_maxAge.toInt()} yrs'),
                      ],
                    ),
                    const SizedBox(height: 20),
                    _buildSubLabel('Height Range (cm)'),
                    const SizedBox(height: 8),
                    _buildRangeSlider(
                      minValue: _minHeight,
                      maxValue: _maxHeight,
                      min: 100,
                      max: 250,
                      divisions: 150,
                      labelBuilder: (value) => '${value.toInt()} cm',
                      onChanged: (min, max) {
                        setState(() {
                          _minHeight = min;
                          _maxHeight = max;
                          _updateAutoGeneratedExpectations();
                        });
                      },
                    ),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        _buildRangeLabel('${_minHeight.toInt()} cm'),
                        _buildRangeLabel('${_maxHeight.toInt()} cm'),
                      ],
                    ),
                    const SizedBox(height: 20),
                    _buildSubLabel('Complexion'),
                    if (submitted && _errors['complexion']!.isNotEmpty)
                      _buildErrorText(_errors['complexion']!),
                    const SizedBox(height: 8),
                    _buildMultiSelectDropdown(
                      selectedItems: _selectedComplexion,
                      options: _complexionOptions,
                      hint: "Choose Complexion",
                      onChanged: (selectedItems) {
                        _handleMultiSelectChange(selectedItems, 'complexion', (items) {
                          setState(() {
                            _selectedComplexion = items;
                            _errors['complexion'] = '';
                          });
                        });
                      },
                      title: 'Complexion',
                      showError: submitted && _errors['complexion']!.isNotEmpty,
                      errorText: _errors['complexion'],
                    ),
                    const SizedBox(height: 16),
                    _buildSubLabel('Body Type'),
                    if (submitted && _errors['bodyType']!.isNotEmpty)
                      _buildErrorText(_errors['bodyType']!),
                    const SizedBox(height: 8),
                    _buildMultiSelectDropdown(
                      selectedItems: _selectedBodyType,
                      options: _bodyTypeOptions,
                      hint: "Choose Body Type",
                      onChanged: (selectedItems) {
                        _handleMultiSelectChange(selectedItems, 'bodyType', (items) {
                          setState(() {
                            _selectedBodyType = items;
                            _errors['bodyType'] = '';
                          });
                        });
                      },
                      title: 'Body Type',
                      showError: submitted && _errors['bodyType']!.isNotEmpty,
                      errorText: _errors['bodyType'],
                    ),
                  ],
                ),
                const SizedBox(height: 16),

                // Basic Preferences Card
                _buildSectionCard(
                  icon: Icons.favorite_rounded,
                  iconColor: const Color(0xFFE91E8C),
                  title: 'Basic Preferences',
                  children: [
                    _buildSubLabel('Marital Status'),
                    if (submitted && _errors['maritalStatus']!.isNotEmpty)
                      _buildErrorText(_errors['maritalStatus']!),
                    const SizedBox(height: 8),
                    _buildMultiSelectDropdown(
                      selectedItems: _selectedMaritalStatus,
                      options: _maritalStatusOptions,
                      hint: "Choose Marital Status",
                      onChanged: (selectedItems) {
                        _handleMultiSelectChange(selectedItems, 'maritalStatus', (items) {
                          setState(() {
                            _selectedMaritalStatus = items;
                            _errors['maritalStatus'] = '';
                          });
                        });
                      },
                      title: 'Marital Status',
                      showError: submitted && _errors['maritalStatus']!.isNotEmpty,
                      errorText: _errors['maritalStatus'],
                    ),
                    if (!_hasAnySelected(_selectedMaritalStatus) &&
                        !_selectedMaritalStatus.contains('Single')) ...[
                      const SizedBox(height: 16),
                      _buildSubLabel('Profile With Children'),
                      if (submitted && _errors['profileWithChildren']!.isNotEmpty)
                        _buildErrorText(_errors['profileWithChildren']!),
                      const SizedBox(height: 8),
                      Row(
                        children: _childrenOptions.map((option) {
                          return Expanded(
                            child: _buildRadioOption(
                              value: option,
                              groupValue: _selectedProfileWithChildren,
                              label: option,
                              onChanged: (value) {
                                _handleSingleSelectChange(value, 'profileWithChildren', (val) {
                                  setState(() {
                                    _selectedProfileWithChildren = val;
                                    _errors['profileWithChildren'] = '';
                                  });
                                });
                              },
                              hasError: submitted && _errors['profileWithChildren']!.isNotEmpty,
                            ),
                          );
                        }).toList(),
                      ),
                    ],
                    const SizedBox(height: 16),
                    _buildSubLabel('Family Type'),
                    if (submitted && _errors['familyType']!.isNotEmpty)
                      _buildErrorText(_errors['familyType']!),
                    const SizedBox(height: 8),
                    _buildMultiSelectDropdown(
                      selectedItems: _selectedFamilyType,
                      options: _familyTypeOptions,
                      hint: "Select Family Type",
                      onChanged: (selectedItems) {
                        _handleMultiSelectChange(selectedItems, 'familyType', (items) {
                          setState(() {
                            _selectedFamilyType = items;
                            _errors['familyType'] = '';
                          });
                        });
                      },
                      title: 'Family Type',
                      showError: submitted && _errors['familyType']!.isNotEmpty,
                      errorText: _errors['familyType'],
                    ),
                  ],
                ),
                const SizedBox(height: 16),

                // Community Details Card
                _buildSectionCard(
                  icon: Icons.groups_rounded,
                  iconColor: const Color(0xFF7B2FF7),
                  title: 'Community Details',
                  children: [
                    _buildSubLabel('Religion'),
                    if (submitted && _errors['religion']!.isNotEmpty)
                      _buildErrorText(_errors['religion']!),
                    const SizedBox(height: 8),
                    _buildMultiSelectDropdown(
                      selectedItems: _selectedReligion,
                      options: _religionOptions,
                      hint: "Select Religion Type",
                      onChanged: (selectedItems) {
                        _handleMultiSelectChange(selectedItems, 'religion', (items) {
                          setState(() {
                            _selectedReligion = items;
                            _errors['religion'] = '';
                          });
                        });
                      },
                      title: 'Religion Type',
                      showError: submitted && _errors['religion']!.isNotEmpty,
                      errorText: _errors['religion'],
                    ),
                    const SizedBox(height: 16),
                    _buildSubLabel('Caste'),
                    if (submitted && _errors['cast']!.isNotEmpty)
                      _buildErrorText(_errors['cast']!),
                    const SizedBox(height: 8),
                    _buildMultiSelectDropdown(
                      selectedItems: _selectedCast,
                      options: _castOptions,
                      hint: "Select Cast Type",
                      onChanged: (selectedItems) {
                        _handleMultiSelectChange(selectedItems, 'cast', (items) {
                          setState(() {
                            _selectedCast = items;
                            _errors['cast'] = '';
                          });
                        });
                      },
                      title: 'Cast Type',
                      showError: submitted && _errors['cast']!.isNotEmpty,
                      errorText: _errors['cast'],
                    ),
                    const SizedBox(height: 16),
                    _buildSubLabel('Sub Caste'),
                    if (submitted && _errors['subCast']!.isNotEmpty)
                      _buildErrorText(_errors['subCast']!),
                    const SizedBox(height: 8),
                    _buildMultiSelectDropdown(
                      selectedItems: _selectedsubCast,
                      options: _subcastOptions,
                      hint: "Select SubCast Type",
                      onChanged: (selectedItems) {
                        _handleMultiSelectChange(selectedItems, 'subCast', (items) {
                          setState(() {
                            _selectedsubCast = items;
                            _errors['subCast'] = '';
                          });
                        });
                      },
                      title: 'SubCast Type',
                      showError: submitted && _errors['subCast']!.isNotEmpty,
                      errorText: _errors['subCast'],
                    ),
                    const SizedBox(height: 16),
                    _buildSubLabel('Mother Tongue'),
                    if (submitted && _errors['motherTongue']!.isNotEmpty)
                      _buildErrorText(_errors['motherTongue']!),
                    const SizedBox(height: 8),
                    _buildMultiSelectDropdown(
                      selectedItems: _selectedMotherTongue,
                      options: _motherTongueOptions,
                      hint: "Select Mother Tongue",
                      onChanged: (selectedItems) {
                        _handleMultiSelectChange(selectedItems, 'motherTongue', (items) {
                          setState(() {
                            _selectedMotherTongue = items;
                            _errors['motherTongue'] = '';
                          });
                        });
                      },
                      title: 'Mother Tongue Type',
                      showError: submitted && _errors['motherTongue']!.isNotEmpty,
                      errorText: _errors['motherTongue'],
                    ),
                  ],
                ),
                const SizedBox(height: 16),

                // Astrological Details Card
                _buildSectionCard(
                  icon: Icons.auto_awesome_rounded,
                  iconColor: const Color(0xFFFF9800),
                  title: 'Astrological Details',
                  children: [
                    _buildSubLabel('Horoscope Belief'),
                    if (submitted && _errors['horoscopeBelief']!.isNotEmpty)
                      _buildErrorText(_errors['horoscopeBelief']!),
                    const SizedBox(height: 8),
                    Row(
                      children: _beliefOptions.map((option) {
                        return Expanded(
                          child: _buildRadioOption(
                            value: option,
                            groupValue: _selectedHoroscopeBelief,
                            label: option,
                            onChanged: (value) {
                              _handleSingleSelectChange(value, 'horoscopeBelief', (val) {
                                setState(() {
                                  _selectedHoroscopeBelief = val;
                                  _errors['horoscopeBelief'] = '';
                                });
                              });
                            },
                            hasError: submitted && _errors['horoscopeBelief']!.isNotEmpty,
                          ),
                        );
                      }).toList(),
                    ),
                    const SizedBox(height: 16),
                    _buildSubLabel('Manglik'),
                    if (submitted && _errors['manglik']!.isNotEmpty)
                      _buildErrorText(_errors['manglik']!),
                    const SizedBox(height: 8),
                    Row(
                      children: _beliefOptions.map((option) {
                        return Expanded(
                          child: _buildRadioOption(
                            value: option,
                            groupValue: _selectedManglik,
                            label: option,
                            onChanged: (value) {
                              _handleSingleSelectChange(value, 'manglik', (val) {
                                setState(() {
                                  _selectedManglik = val;
                                  _errors['manglik'] = '';
                                });
                              });
                            },
                            hasError: submitted && _errors['manglik']!.isNotEmpty,
                          ),
                        );
                      }).toList(),
                    ),
                  ],
                ),
                const SizedBox(height: 16),

                // Location Preferences Card
                _buildSectionCard(
                  icon: Icons.location_on_rounded,
                  iconColor: const Color(0xFF2196F3),
                  title: 'Location Preferences',
                  children: [
                    _buildSubLabel('Country'),
                    if (submitted && _errors['country']!.isNotEmpty)
                      _buildErrorText(_errors['country']!),
                    const SizedBox(height: 8),
                    _buildMultiSelectDropdown(
                      selectedItems: _selectedCountry,
                      options: _countries.map((c) => c.name).toList(),
                      hint: "Select Country",
                      onChanged: _handleCountryChange,
                      title: 'Country',
                      showError: submitted && _errors['country']!.isNotEmpty,
                      errorText: _errors['country'],
                      isLoading: _loadingCountries,
                      disabled: _loadingCountries,
                    ),
                    if (_selectedCountry.isNotEmpty && !_hasAnySelected(_selectedCountry)) ...[
                      const SizedBox(height: 16),
                      _buildSubLabel('State / Province'),
                      if (submitted && _errors['state']!.isNotEmpty)
                        _buildErrorText(_errors['state']!),
                      const SizedBox(height: 8),
                      _buildMultiSelectDropdown(
                        selectedItems: _selectedState,
                        options: _allStates.map((s) => s.name).toList(),
                        hint: _loadingStates ? "Loading states..." : "State / Province",
                        onChanged: _handleStateChange,
                        title: 'State / Province',
                        showError: submitted && _errors['state']!.isNotEmpty,
                        errorText: _errors['state'],
                        isLoading: _loadingStates,
                        disabled: _loadingStates,
                      ),
                    ],
                    if (_selectedState.isNotEmpty && !_hasAnySelected(_selectedState)) ...[
                      const SizedBox(height: 16),
                      _buildSubLabel('City'),
                      if (submitted && _errors['city']!.isNotEmpty)
                        _buildErrorText(_errors['city']!),
                      const SizedBox(height: 8),
                      _buildMultiSelectDropdown(
                        selectedItems: _selectedCity,
                        options: _allCities.map((c) => c.name).toList(),
                        hint: _loadingCities ? "Loading cities..." : "City",
                        onChanged: _handleCityChange,
                        title: 'Cities',
                        showError: submitted && _errors['city']!.isNotEmpty,
                        errorText: _errors['city'],
                        isLoading: _loadingCities,
                        disabled: _loadingCities,
                      ),
                    ],
                  ],
                ),
                const SizedBox(height: 16),

                // Education & Career Card
                _buildSectionCard(
                  icon: Icons.school_rounded,
                  iconColor: const Color(0xFF4CAF50),
                  title: 'Education & Career',
                  children: [
                    _buildSubLabel('Qualification'),
                    if (submitted && _errors['qualification']!.isNotEmpty)
                      _buildErrorText(_errors['qualification']!),
                    const SizedBox(height: 8),
                    _buildMultiSelectDropdown(
                      selectedItems: _selectedQualification,
                      options: _qualificationOptions,
                      hint: "Select Your Qualification",
                      onChanged: (selectedItems) {
                        _handleMultiSelectChange(selectedItems, 'qualification', (items) {
                          setState(() {
                            _selectedQualification = items;
                            _errors['qualification'] = '';
                          });
                        });
                      },
                      title: 'Qualifications',
                      showError: submitted && _errors['qualification']!.isNotEmpty,
                      errorText: _errors['qualification'],
                    ),
                    const SizedBox(height: 16),
                    _buildSubLabel('Education Medium'),
                    if (submitted && _errors['educationMedium']!.isNotEmpty)
                      _buildErrorText(_errors['educationMedium']!),
                    const SizedBox(height: 8),
                    _buildMultiSelectDropdown(
                      selectedItems: _selectedEducationMedium,
                      options: _educationMediumOptions,
                      hint: "Select Education Medium",
                      onChanged: (selectedItems) {
                        _handleMultiSelectChange(selectedItems, 'educationMedium', (items) {
                          setState(() {
                            _selectedEducationMedium = items;
                            _errors['educationMedium'] = '';
                          });
                        });
                      },
                      title: 'Education Medium',
                      showError: submitted && _errors['educationMedium']!.isNotEmpty,
                      errorText: _errors['educationMedium'],
                    ),
                    const SizedBox(height: 16),
                    _buildSubLabel('Profession'),
                    if (submitted && _errors['profession']!.isNotEmpty)
                      _buildErrorText(_errors['profession']!),
                    const SizedBox(height: 8),
                    _buildMultiSelectDropdown(
                      selectedItems: _selectedProfession,
                      options: _professionOptions,
                      hint: "Select Your Profession",
                      onChanged: (selectedItems) {
                        _handleMultiSelectChange(selectedItems, 'profession', (items) {
                          setState(() {
                            _selectedProfession = items;
                            _errors['profession'] = '';
                          });
                        });
                      },
                      title: 'Profession',
                      showError: submitted && _errors['profession']!.isNotEmpty,
                      errorText: _errors['profession'],
                    ),
                    const SizedBox(height: 16),
                    _buildSubLabel('Working With'),
                    if (submitted && _errors['workingWith']!.isNotEmpty)
                      _buildErrorText(_errors['workingWith']!),
                    const SizedBox(height: 8),
                    _buildMultiSelectDropdown(
                      selectedItems: _selectedWorkingWith,
                      options: _workingWithOptions,
                      hint: "Select Working With",
                      onChanged: (selectedItems) {
                        _handleMultiSelectChange(selectedItems, 'workingWith', (items) {
                          setState(() {
                            _selectedWorkingWith = items;
                            _errors['workingWith'] = '';
                          });
                        });
                      },
                      title: 'Working With',
                      showError: submitted && _errors['workingWith']!.isNotEmpty,
                      errorText: _errors['workingWith'],
                    ),
                    const SizedBox(height: 16),
                    _buildSubLabel('Annual Income'),
                    if (submitted && _errors['annualIncome']!.isNotEmpty)
                      _buildErrorText(_errors['annualIncome']!),
                    const SizedBox(height: 8),
                    _buildMultiSelectDropdown(
                      selectedItems: _selectedAnnualIncome,
                      options: _annualIncomeOptions,
                      hint: "Select Annual Income",
                      onChanged: (selectedItems) {
                        _handleMultiSelectChange(selectedItems, 'annualIncome', (items) {
                          setState(() {
                            _selectedAnnualIncome = items;
                            _errors['annualIncome'] = '';
                          });
                        });
                      },
                      title: 'Annual Income',
                      showError: submitted && _errors['annualIncome']!.isNotEmpty,
                      errorText: _errors['annualIncome'],
                    ),
                  ],
                ),
                const SizedBox(height: 16),

                // Lifestyle Preferences Card
                _buildSectionCard(
                  icon: Icons.spa_rounded,
                  iconColor: const Color(0xFF009688),
                  title: 'Lifestyle Preferences',
                  children: [
                    _buildSubLabel('Diet'),
                    if (submitted && _errors['diet']!.isNotEmpty)
                      _buildErrorText(_errors['diet']!),
                    const SizedBox(height: 8),
                    _buildMultiSelectDropdown(
                      selectedItems: _selectedDiet,
                      options: _dietOptions,
                      hint: "Choose Diet",
                      onChanged: (selectedItems) {
                        _handleMultiSelectChange(selectedItems, 'diet', (items) {
                          setState(() {
                            _selectedDiet = items;
                            _errors['diet'] = '';
                          });
                        });
                      },
                      title: 'Diets',
                      showError: submitted && _errors['diet']!.isNotEmpty,
                      errorText: _errors['diet'],
                    ),
                    const SizedBox(height: 16),
                    _buildSubLabel('Smoke Acceptance'),
                    if (submitted && _errors['smokeAcceptance']!.isNotEmpty)
                      _buildErrorText(_errors['smokeAcceptance']!),
                    const SizedBox(height: 8),
                    Row(
                      children: _beliefOptions.map((option) {
                        return Expanded(
                          child: _buildRadioOption(
                            value: option,
                            groupValue: _selectedSmokeAcceptance,
                            label: option,
                            onChanged: (value) {
                              _handleSingleSelectChange(value, 'smokeAcceptance', (val) {
                                setState(() {
                                  _selectedSmokeAcceptance = val;
                                  _errors['smokeAcceptance'] = '';
                                });
                              });
                            },
                            hasError: submitted && _errors['smokeAcceptance']!.isNotEmpty,
                          ),
                        );
                      }).toList(),
                    ),
                    const SizedBox(height: 16),
                    _buildSubLabel('Alcohol Acceptance'),
                    if (submitted && _errors['alcoholAcceptance']!.isNotEmpty)
                      _buildErrorText(_errors['alcoholAcceptance']!),
                    const SizedBox(height: 8),
                    Row(
                      children: _beliefOptions.map((option) {
                        return Expanded(
                          child: _buildRadioOption(
                            value: option,
                            groupValue: _selectedAlcoholAcceptance,
                            label: option,
                            onChanged: (value) {
                              _handleSingleSelectChange(value, 'alcoholAcceptance', (val) {
                                setState(() {
                                  _selectedAlcoholAcceptance = val;
                                  _errors['alcoholAcceptance'] = '';
                                });
                              });
                            },
                            hasError: submitted && _errors['alcoholAcceptance']!.isNotEmpty,
                          ),
                        );
                      }).toList(),
                    ),
                    const SizedBox(height: 16),
                    _buildSubLabel('Disability Acceptance'),
                    if (submitted && _errors['disabilityAcceptance']!.isNotEmpty)
                      _buildErrorText(_errors['disabilityAcceptance']!),
                    const SizedBox(height: 8),
                    Row(
                      children: _beliefOptions.map((option) {
                        return Expanded(
                          child: _buildRadioOption(
                            value: option,
                            groupValue: _selectedDisabilityAcceptance,
                            label: option,
                            onChanged: (value) {
                              _handleSingleSelectChange(value, 'disabilityAcceptance', (val) {
                                setState(() {
                                  _selectedDisabilityAcceptance = val;
                                  _errors['disabilityAcceptance'] = '';
                                });
                              });
                            },
                            hasError: submitted && _errors['disabilityAcceptance']!.isNotEmpty,
                          ),
                        );
                      }).toList(),
                    ),
                  ],
                ),
                const SizedBox(height: 16),

                // Your Expectations Card
                _buildSectionCard(
                  icon: Icons.auto_fix_high_rounded,
                  iconColor: const Color(0xFFFF5722),
                  title: 'Your Expectations',
                  children: [
                    if (_autoGeneratedExpectations.isNotEmpty) ...[
                      Container(
                        margin: const EdgeInsets.only(bottom: 16),
                        padding: const EdgeInsets.all(14),
                        decoration: BoxDecoration(
                          color: const Color(0xFFE64B37).withOpacity(0.05),
                          borderRadius: BorderRadius.circular(12),
                          border: Border.all(
                            color: const Color(0xFFE64B37).withOpacity(0.18),
                          ),
                        ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const Row(
                              children: [
                                Icon(Icons.auto_awesome, size: 15, color: Color(0xFFE64B37)),
                                SizedBox(width: 6),
                                Flexible(
                                  child: Text(
                                    "Auto-generated from your selections:",
                                    style: TextStyle(
                                      fontSize: 12,
                                      fontWeight: FontWeight.w600,
                                      color: Color(0xFFE64B37),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                            const SizedBox(height: 10),
                            ..._autoGeneratedExpectations.map((expectation) {
                              return Padding(
                                padding: const EdgeInsets.symmetric(vertical: 2),
                                child: Row(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    const Text('• ',
                                        style: TextStyle(fontSize: 12, color: Color(0xFF4A4A68))),
                                    Expanded(
                                      child: Text(
                                        expectation,
                                        style: const TextStyle(
                                            fontSize: 12, color: Color(0xFF4A4A68)),
                                      ),
                                    ),
                                  ],
                                ),
                              );
                            }).toList(),
                          ],
                        ),
                      ),
                    ],
                    _buildSubLabel('Any Other Expectation', isRequired: false),
                    const SizedBox(height: 4),
                    Text(
                      'Optional - Add any additional preferences',
                      style: TextStyle(
                        fontSize: 11,
                        color: Colors.grey[600],
                        fontStyle: FontStyle.italic,
                      ),
                    ),
                    const SizedBox(height: 8),
                    Container(
                      height: 120,
                      padding: const EdgeInsets.symmetric(horizontal: 15),
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(15),
                        border: Border.all(color: const Color(0xFF48A54C), width: 1.6),
                      ),
                      child: TextField(
                        controller: _otherExpectationsController,
                        decoration: const InputDecoration(
                          border: InputBorder.none,
                          hintText: "Enter your other expectations...",
                          hintStyle: TextStyle(fontSize: 16, color: Colors.black54),
                        ),
                        maxLines: null,
                        expands: true,
                        textAlignVertical: TextAlignVertical.top,
                        onChanged: (value) {},
                      ),
                    ),
                    const SizedBox(height: 10),
                    Align(
                      alignment: Alignment.centerRight,
                      child: GestureDetector(
                        onTap: _updateAutoGeneratedExpectations,
                        child: Container(
                          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                          decoration: BoxDecoration(
                            color: Colors.blue[50],
                            borderRadius: BorderRadius.circular(20),
                            border: Border.all(color: Colors.blue),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              Icon(Icons.autorenew, size: 14, color: Colors.blue[700]),
                              const SizedBox(width: 6),
                              Text(
                                "Regenerate Expectations",
                                style: TextStyle(
                                  fontSize: 12,
                                  color: Colors.blue[700],
                                  fontWeight: FontWeight.w500,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 24),
              ],
            ),
          ),

          // Loading overlay
          if (isLoading)
            Container(
              color: Colors.black.withOpacity(0.3),
              child: const Center(
                child: CircularProgressIndicator(
                  valueColor: AlwaysStoppedAnimation<Color>(Color(0xFFE64B37)),
                ),
              ),
            ),
        ],
      ),
    );
  }

  // ── Hero Header ──────────────────────────────────────────────────────────────
  Widget _buildHeroHeader() {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.symmetric(vertical: 28, horizontal: 20),
      decoration: BoxDecoration(
        gradient: const LinearGradient(
          colors: [Color(0xFFFFECE8), Color(0xFFFFF0F5)],
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
        ),
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: const Color(0xFFE64B37).withOpacity(0.12),
            blurRadius: 18,
            offset: const Offset(0, 6),
          ),
        ],
      ),
      child: Column(
        children: [
          const Image(
            image: AssetImage('assets/images/partner.png'),
            height: 130,
            fit: BoxFit.contain,
          ),
          const SizedBox(height: 14),
          const Text(
            "Find Your Perfect Match",
            style: TextStyle(
              fontSize: 18,
              fontWeight: FontWeight.w700,
              color: Color(0xFFE64B37),
            ),
          ),
          const SizedBox(height: 6),
          Text(
            "Set your partner preferences to help us\nfind the most compatible profiles for you.",
            textAlign: TextAlign.center,
            style: TextStyle(
              fontSize: 13,
              color: Colors.grey[600],
              height: 1.5,
            ),
          ),
        ],
      ),
    );
  }

  // ── Section Card ─────────────────────────────────────────────────────────────
  Widget _buildSectionCard({
    required IconData icon,
    required Color iconColor,
    required String title,
    required List<Widget> children,
  }) {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.06),
            blurRadius: 12,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Colored header
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
            decoration: BoxDecoration(
              color: iconColor.withOpacity(0.08),
              borderRadius: const BorderRadius.vertical(top: Radius.circular(16)),
            ),
            child: Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: iconColor.withOpacity(0.15),
                    shape: BoxShape.circle,
                  ),
                  child: Icon(icon, color: iconColor, size: 20),
                ),
                const SizedBox(width: 12),
                Text(
                  title,
                  style: TextStyle(
                    fontSize: 15,
                    fontWeight: FontWeight.w700,
                    color: iconColor,
                  ),
                ),
              ],
            ),
          ),
          // Content
          Padding(
            padding: const EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: children,
            ),
          ),
        ],
      ),
    );
  }

  // ── Sub-label ────────────────────────────────────────────────────────────────
  Widget _buildSubLabel(String label, {bool isRequired = true}) {
    return Row(
      children: [
        Text(
          label,
          style: const TextStyle(
            fontSize: 13,
            fontWeight: FontWeight.w600,
            color: Color(0xFF4A4A68),
          ),
        ),
        if (isRequired) ...[
          const SizedBox(width: 4),
          const Text(
            '*',
            style: TextStyle(
              fontSize: 14,
              fontWeight: FontWeight.w700,
              color: Color(0xFFE64B37),
            ),
          ),
        ],
      ],
    );
  }

  // ── Range pill label ─────────────────────────────────────────────────────────
  Widget _buildRangeLabel(String text) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
      decoration: BoxDecoration(
        color: const Color(0xFFE64B37).withOpacity(0.08),
        borderRadius: BorderRadius.circular(20),
      ),
      child: Text(
        text,
        style: const TextStyle(
          fontSize: 12,
          fontWeight: FontWeight.w600,
          color: Color(0xFFE64B37),
        ),
      ),
    );
  }

  // ── Bottom navigation bar ────────────────────────────────────────────────────
  Widget _buildBottomBar() {
    return Container(
      padding: const EdgeInsets.fromLTRB(16, 12, 16, 20),
      decoration: BoxDecoration(
        color: Colors.white,
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.08),
            blurRadius: 16,
            offset: const Offset(0, -4),
          ),
        ],
      ),
      child: Row(
        children: [
          Expanded(
            child: _buildButton(
              text: "Previous",
              isPrimary: false,
              onPressed: isLoading ? null : () => Navigator.pop(context),
            ),
          ),
          const SizedBox(width: 14),
          Expanded(
            flex: 2,
            child: _buildButton(
              text: isLoading ? "Saving..." : "Save & Continue",
              isPrimary: true,
              onPressed: isLoading ? null : _validateAndSubmit,
            ),
          ),
        ],
      ),
    );
  }

  // Multi-select dropdown widget with modern styled trigger
  Widget _buildMultiSelectDropdown({
    required List<String> selectedItems,
    required List<String> options,
    required String hint,
    required Function(List<String>) onChanged,
    String? title,
    bool showError = false,
    String? errorText,
    bool isLoading = false,
    bool disabled = false,
  }) {
    final hasSelection = selectedItems.isNotEmpty;
    final hasError = showError && (errorText?.isNotEmpty ?? false);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        GestureDetector(
          onTap: disabled || isLoading
              ? null
              : () {
                  _showMultiSelectDialog(
                    context: context,
                    selectedItems: selectedItems,
                    options: options,
                    hint: hint,
                    onChanged: onChanged,
                    title: title ?? hint,
                  );
                },
          child: AnimatedContainer(
            duration: const Duration(milliseconds: 200),
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
            decoration: BoxDecoration(
              color: hasError
                  ? Colors.red.withOpacity(0.04)
                  : hasSelection
                      ? const Color(0xFF48A54C).withOpacity(0.06)
                      : Colors.grey.withOpacity(0.04),
              borderRadius: BorderRadius.circular(12),
              border: Border.all(
                color: hasError
                    ? Colors.red
                    : hasSelection
                        ? const Color(0xFF48A54C)
                        : Colors.grey.shade300,
                width: hasSelection && !hasError ? 1.8 : 1.4,
              ),
            ),
            child: Row(
              children: [
                if (isLoading) ...[
                  SizedBox(
                    width: 18,
                    height: 18,
                    child: CircularProgressIndicator(
                      strokeWidth: 2,
                      valueColor:
                          const AlwaysStoppedAnimation<Color>(Color(0xFFE64B37)),
                    ),
                  ),
                  const SizedBox(width: 10),
                ],
                Expanded(
                  child: Text(
                    isLoading
                        ? hint
                        : !hasSelection
                            ? hint
                            : selectedItems.contains('Any')
                                ? "Any (All options)"
                                : "${selectedItems.length} selected",
                    style: TextStyle(
                      fontSize: 15,
                      color: isLoading || !hasSelection
                          ? Colors.grey.shade500
                          : const Color(0xFF2D2D2D),
                      fontWeight:
                          hasSelection ? FontWeight.w500 : FontWeight.normal,
                    ),
                  ),
                ),
                if (hasSelection && !selectedItems.contains('Any')) ...[
                  Container(
                    padding:
                        const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                    decoration: BoxDecoration(
                      color: const Color(0xFF48A54C),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: Text(
                      '${selectedItems.length}',
                      style: const TextStyle(
                        color: Colors.white,
                        fontSize: 11,
                        fontWeight: FontWeight.w700,
                      ),
                    ),
                  ),
                  const SizedBox(width: 8),
                ],
                Icon(
                  Icons.keyboard_arrow_down_rounded,
                  color: disabled || isLoading
                      ? Colors.grey.shade400
                      : hasSelection
                          ? const Color(0xFF48A54C)
                          : Colors.grey.shade500,
                  size: 22,
                ),
              ],
            ),
          ),
        ),
        if (hasError)
          Padding(
            padding: const EdgeInsets.only(top: 4.0),
            child: Text(
              errorText!,
              style: const TextStyle(color: Colors.red, fontSize: 12),
            ),
          ),
      ],
    );
  }

  void _showMultiSelectDialog({
    required BuildContext context,
    required List<String> selectedItems,
    required List<String> options,
    required String hint,
    required Function(List<String>) onChanged,
    required String title,
  }) {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.white,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
      ),
      builder: (context) {
        return FractionallySizedBox(
          heightFactor: 0.75,
          child: _MultiSelectBottomSheet(
            selectedItems: selectedItems,
            options: options,
            title: title,
            onChanged: onChanged,
          ),
        );
      },
    );
  }

  Widget _buildErrorText(String error) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 4.0, top: 4.0),
      child: Text(
        error,
        style: const TextStyle(
          color: Colors.red,
          fontSize: 12,
        ),
      ),
    );
  }

  Widget _buildRangeSlider({
    required double minValue,
    required double maxValue,
    required double min,
    required double max,
    required int divisions,
    required String Function(double) labelBuilder,
    required Function(double, double) onChanged,
  }) {
    return RangeSlider(
      values: RangeValues(minValue, maxValue),
      min: min,
      max: max,
      divisions: divisions,
      labels: RangeLabels(
        labelBuilder(minValue),
        labelBuilder(maxValue),
      ),
      activeColor: const Color(0xFFE64B37),
      inactiveColor: Colors.grey[300],
      onChanged: (RangeValues values) {
        onChanged(values.start, values.end);
      },
    );
  }

  Widget _buildSectionTitle(String title) {
    return _buildSubLabel(title);
  }

  Widget _buildDivider() {
    return Divider(
      color: Colors.grey.shade200,
      height: 1,
      thickness: 1,
    );
  }

  Widget _buildRadioOption({
    required String value,
    required String? groupValue,
    required String label,
    required Function(String) onChanged,
    bool hasError = false,
  }) {
    final isSelected = groupValue == value;

    return GestureDetector(
      onTap: () => onChanged(value),
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 200),
        margin: const EdgeInsets.symmetric(horizontal: 2),
        height: 44,
        decoration: BoxDecoration(
          gradient: isSelected
              ? const LinearGradient(
                  colors: [Color(0xFFE64B37), Color(0xFFE62255)],
                  begin: Alignment.topLeft,
                  end: Alignment.bottomRight,
                )
              : null,
          color: isSelected ? null : Colors.white,
          borderRadius: BorderRadius.circular(10),
          border: Border.all(
            color: hasError
                ? Colors.red
                : isSelected
                    ? Colors.transparent
                    : Colors.grey.shade300,
            width: 1.4,
          ),
          boxShadow: isSelected
              ? [
                  BoxShadow(
                    color: const Color(0xFFE64B37).withOpacity(0.3),
                    blurRadius: 6,
                    offset: const Offset(0, 3),
                  )
                ]
              : null,
        ),
        child: Center(
          child: Text(
            label,
            style: TextStyle(
              fontSize: 12,
              fontWeight: isSelected ? FontWeight.w700 : FontWeight.w500,
              color: isSelected ? Colors.white : const Color(0xFF4A4A68),
            ),
            textAlign: TextAlign.center,
            maxLines: 1,
            overflow: TextOverflow.ellipsis,
          ),
        ),
      ),
    );
  }

  Widget _buildButton({
    required String text,
    required bool isPrimary,
    required VoidCallback? onPressed,
  }) {
    return Container(
      height: 52,
      decoration: BoxDecoration(
        gradient: isPrimary && onPressed != null
            ? const LinearGradient(
                colors: [Color(0xFFE64B37), Color(0xFFE62255)],
                begin: Alignment.centerLeft,
                end: Alignment.centerRight,
              )
            : LinearGradient(
                colors: [Colors.grey.shade300, Colors.grey.shade200],
              ),
        borderRadius: BorderRadius.circular(30),
        boxShadow: isPrimary && onPressed != null
            ? [
                BoxShadow(
                  color: const Color(0xFFE64B37).withOpacity(0.35),
                  blurRadius: 12,
                  offset: const Offset(0, 5),
                ),
              ]
            : null,
      ),
      child: Material(
        color: Colors.transparent,
        child: InkWell(
          borderRadius: BorderRadius.circular(30),
          onTap: onPressed,
          child: Center(
            child: Text(
              text,
              style: TextStyle(
                color: isPrimary && onPressed != null
                    ? Colors.white
                    : Colors.grey.shade600,
                fontSize: 15,
                fontWeight: FontWeight.w700,
                letterSpacing: 0.3,
              ),
            ),
          ),
        ),
      ),
    );
  }

  Widget _progressBubble(double progress, String label) {
    const size = 40.0;
    return SizedBox(
      height: size,
      width: size,
      child: Stack(
        alignment: Alignment.center,
        children: [
          Container(
            height: size,
            width: size,
            decoration: BoxDecoration(
              color: Colors.white.withOpacity(0.25),
              shape: BoxShape.circle,
            ),
          ),
          SizedBox(
            height: size,
            width: size,
            child: CircularProgressIndicator(
              value: progress,
              strokeWidth: 3.0,
              valueColor: const AlwaysStoppedAnimation(Colors.white),
              backgroundColor: Colors.white.withOpacity(0.3),
            ),
          ),
          Text(
            label,
            style: const TextStyle(
              fontSize: 10,
              fontWeight: FontWeight.w800,
              color: Colors.white,
            ),
          ),
        ],
      ),
    );
  }

  void _validateAndSubmit() async {
    setState(() {
      submitted = true;
    });

    if (!_validateForm()) {
      _showError("Please fill all required fields correctly");
      return;
    }

    setState(() {
      isLoading = true;
    });

    await _submitPartnerPreferences();

    setState(() {
      isLoading = false;
    });
  }

  // Add this method to load saved partner preferences
  Future<void> _loadSavedPreferences() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final userDataString = prefs.getString('user_data');

      if (userDataString == null) {
        return;
      }

      final decodedUserData = jsonDecode(userDataString);
      if (decodedUserData is! Map<String, dynamic>) {
        return;
      }

      final userData = decodedUserData;
      final userId = userData["id"]?.toString() ?? '';

      if (userId.isEmpty) {
        return;
      }

      _applyAgeBoundsFromUserData(userData);

      setState(() {
        isLoading = true;
      });

      // Always fetch fresh data from API to ensure consistency
      // This fixes the issue where editing multiple times causes data to disappear
      try {
        final response = await http.get(
          Uri.parse("${kApiBaseUrl}/Api2/get_partner_preferences.php?userid=$userId"),
        ).timeout(const Duration(seconds: 30));

        if (response.statusCode == 200) {
          final result = jsonDecode(response.body);

          if (result['status'] == 'success' && result['data'] != null) {
            _applyPreferenceData(Map<String, dynamic>.from(result['data']));
          } else if (widget.initialData != null && widget.initialData!.isNotEmpty) {
            // Fallback to initialData only if API fetch fails
            _applyPreferenceData(widget.initialData!);
          }
        } else if (widget.initialData != null && widget.initialData!.isNotEmpty) {
          // Fallback to initialData if API returns non-200 status
          _applyPreferenceData(widget.initialData!);
        }
      } catch (apiError) {
        print("Error fetching from API: $apiError");
        // Fallback to initialData if API call throws an exception
        if (widget.initialData != null && widget.initialData!.isNotEmpty) {
          _applyPreferenceData(widget.initialData!);
        }
      }
    } catch (e) {
      print("Error loading saved preferences: $e");
    } finally {
      setState(() {
        isLoading = false;
      });
    }
  }

// Update initState to load saved data


  _submitPartnerPreferences() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final userDataString = prefs.getString('user_data');

      if (userDataString == null) {
        _showError("User data not found. Please login again.");
        return;
      }

      final userData = jsonDecode(userDataString);
      final userId = int.tryParse(userData["id"]?.toString() ?? '0');

      if (userId == null || userId == 0) {
        _showError("Invalid user ID");
        return;
      }

      // Prepare the data as JSON
      final Map<String, dynamic> body = {
        "userid": userId.toString(),
        "minage": _minAge.toInt().toString(),
        "maxage": _maxAge.toInt().toString(),
        "minheight": _minHeight.toInt().toString(),
        "maxheight": _maxHeight.toInt().toString(),
        "maritalstatus": _selectedMaritalStatus.join(","),
        "profilewithchild": _selectedProfileWithChildren ?? "No child",
        "familytype": _selectedFamilyType.join(","),
        "religion": _selectedReligion.join(","),
        "caste": _selectedCast.join(","),
        "subcaste": _selectedsubCast.join(","),
        "mothertongue": _selectedMotherTongue.join(","),
        "horoscopebelief": _selectedHoroscopeBelief ?? "",
        "manglik": _selectedManglik ?? "",
        "country": _getCountryIds(_selectedCountry).join(","),
        "state": _getStateIds(_selectedState).join(","),
        "city": _getCityIds(_selectedCity).join(","),
        "qualification": _selectedQualification.join(","),
        "educationmedium": _selectedEducationMedium.join(","),
        "profession": _selectedProfession.join(","),
        "workingwith": _selectedWorkingWith.join(","),
        "annualincome": _selectedAnnualIncome.join(","),
        "diet": _selectedDiet.join(","),
        "smokeaccept": _selectedSmokeAcceptance ?? "",
        "drinkaccept": _selectedAlcoholAcceptance ?? "",
        "disabilityaccept": _selectedDisabilityAcceptance ?? "",
        "complexion": _selectedComplexion.join(","),
        "bodytype": _selectedBodyType.join(","),
        "otherexpectation": _otherExpectationsController.text.trim(),
      };

      print("Sending JSON data: $body");

      final response = await http.post(
        Uri.parse("${kApiBaseUrl}/Api2/user_partner.php"),
        body: jsonEncode(body),
        headers: {
          "Content-Type": "application/json; charset=UTF-8",
        },
      ).timeout(const Duration(seconds: 30));

      print("Response status: ${response.statusCode}");
      print("Response body: ${response.body}");

      if (response.statusCode == 200) {
        final result = jsonDecode(response.body);

        if (result["status"] == "success") {
          // Update page number
          _showSuccess("Partner preferences saved successfully!");
          // Navigate after a short delay
          Navigator.pop(context);
        } else {
          _showError(result["message"] ?? "Failed to update progress");
        }
      } else {
        String errorMsg = "Unknown error occurred (${response.statusCode})";
        try {
          final result = jsonDecode(response.body);
          errorMsg = result["message"] ?? errorMsg;
        } catch (_) {}
        print("Non-200 response (${response.statusCode}): ${response.body.substring(0, response.body.length.clamp(0, 500))}");
        _showError(errorMsg);
      }
    } on FormatException catch (e) {
      print("JSON Format Error: $e");
      _showError("Server response format error. Please try again.");
    } on http.ClientException catch (e) {
      print("Network Error: $e");
      _showError("Network error. Please check your connection.");
    } on TimeoutException catch (e) {
      print("Timeout Error: $e");
      _showError("Request timeout. Please try again.");
    } catch (e) {
      print("Unexpected Error: $e");
      _showError("Something went wrong. Please try again.");
    }
  }

  void _showError(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: Colors.red,
        duration: const Duration(seconds: 3),
        behavior: SnackBarBehavior.floating,
      ),
    );
  }

  void _showSuccess(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: Colors.green,
        duration: const Duration(seconds: 2),
        behavior: SnackBarBehavior.floating,
      ),
    );
  }

  @override
  void dispose() {
    _otherExpectationsController.dispose();
    super.dispose();
  }
}

// Multi-select bottom sheet with search
class _MultiSelectBottomSheet extends StatefulWidget {
  final List<String> selectedItems;
  final List<String> options;
  final String title;
  final Function(List<String>) onChanged;

  const _MultiSelectBottomSheet({
    required this.selectedItems,
    required this.options,
    required this.title,
    required this.onChanged,
  });

  @override
  State<_MultiSelectBottomSheet> createState() => _MultiSelectBottomSheetState();
}

class _MultiSelectBottomSheetState extends State<_MultiSelectBottomSheet> {
  late List<String> _currentSelection;
  final TextEditingController _searchController = TextEditingController();

  bool get _showSearch => widget.options.length >= 5;

  List<String> get _visibleOptions {
    final query = _searchController.text.trim().toLowerCase();

    return widget.options.where((option) {
      if (_currentSelection.contains(option)) {
        return false;
      }

      if (!_showSearch || query.isEmpty) {
        return true;
      }

      return option.toLowerCase().contains(query);
    }).toList();
  }

  void _updateParentSelection() {
    widget.onChanged(List<String>.from(_currentSelection));
  }

  @override
  void initState() {
    super.initState();
    _currentSelection = List.from(widget.selectedItems);
  }

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Expanded(
                  child: Text(
                    widget.title,
                    style: const TextStyle(
                      fontSize: 20,
                      fontWeight: FontWeight.bold,
                      color: Color(0xFFE64B37),
                    ),
                  ),
                ),
                IconButton(
                  onPressed: () => Navigator.pop(context),
                  icon: const Icon(Icons.close),
                ),
              ],
            ),
            const SizedBox(height: 12),

            Container(
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
              decoration: BoxDecoration(
                color: const Color(0xFFE64B37).withOpacity(0.08),
                borderRadius: BorderRadius.circular(10),
                border: Border.all(
                  color: const Color(0xFFE64B37).withOpacity(0.2),
                ),
              ),
              child: Text(
                '${_currentSelection.length} selected',
                style: const TextStyle(
                  color: Color(0xFFE64B37),
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),

            if (_currentSelection.isNotEmpty) ...[
              const SizedBox(height: 12),
              Wrap(
                spacing: 8,
                runSpacing: 8,
                children: _currentSelection.map((item) {
                  return Chip(
                    label: Text(item),
                    backgroundColor: const Color(0xFFE64B37).withOpacity(0.1),
                    deleteIcon: const Icon(Icons.close, size: 16),
                    onDeleted: () {
                      setState(() {
                        _currentSelection.remove(item);
                      });
                      _updateParentSelection();
                    },
                    labelStyle: const TextStyle(fontSize: 13),
                  );
                }).toList(),
              ),
            ],

            if (_showSearch) ...[
              const SizedBox(height: 12),
              TextField(
                controller: _searchController,
                autofocus: true,
                textInputAction: TextInputAction.search,
                onChanged: (_) => setState(() {}),
                decoration: InputDecoration(
                  hintText: "Search...",
                  prefixIcon: const Icon(Icons.search),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(30),
                  ),
                  contentPadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 10),
                ),
              ),
            ],
            const SizedBox(height: 16),

            Expanded(
              child: _visibleOptions.isEmpty
                  ? Center(
                child: Text(
                  _showSearch && _searchController.text.trim().isNotEmpty
                      ? 'No options found'
                      : 'All options already selected',
                ),
              )
                  : ListView.builder(
                itemCount: _visibleOptions.length,
                itemBuilder: (context, index) {
                  final option = _visibleOptions[index];

                  return ListTile(
                    title: Text(option),
                    trailing: const Icon(Icons.add_circle_outline),
                    onTap: () {
                      setState(() {
                        if (option == 'Any') {
                          _currentSelection = ['Any'];
                        } else {
                          _currentSelection.remove('Any');
                          _currentSelection.add(option);
                        }
                      });
                      _updateParentSelection();
                      Navigator.pop(context);
                    },
                  );
                },
              ),
            ),

            const SizedBox(height: 16),
            Row(
              children: [
                Expanded(
                  child: OutlinedButton(
                    onPressed: () {
                      setState(() {
                        _currentSelection.clear();
                      });
                      _updateParentSelection();
                    },
                    child: const Text('Clear All'),
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: ElevatedButton(
                    onPressed: () => Navigator.pop(context),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: const Color(0xFFE64B37),
                      padding: const EdgeInsets.symmetric(vertical: 16),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                    ),
                    child: const Text(
                      'Done',
                      style: TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.w600,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
